openapi: 3.0.0
info:
  title: Images
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/imaging/v2
tags:
- description: Groups operations that provide details about your images.
  name: Images
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-images.yaml
paths:
  /network/{network}/images:
    $ref: paths/images.yaml
  /network/{network}/images/{imageId}:
    $ref: paths/image.yaml
