openapi: 3.0.0
info:
  title: Image & Video Manager policy sets
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/imaging/v2
tags:
- description: Groups operations that manage your policy sets.
  name: Policy sets
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-policy-sets.yaml
paths:
  /policysets:
    $ref: paths/policy-sets.yaml
  /policysets/{policySetId}:
    $ref: paths/policy-set.yaml
