openapi: 3.0.0
info:
  title: Log error details
  version: '2'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/imaging/v2
tags:
- description: Groups operations that provide error details about requested transformations.
  name: Errors
x-akamai:
  auth-type: EDGE_GRID
  file-path: 04-log-error-details.yaml
paths:
  /network/{network}/details/errors:
    parameters:
    - $ref: parameters/network-path.yaml
    - $ref: parameters/contract-id-header.yaml
    - $ref: parameters/policy-set-id-header.yaml
    get:
      operationId: get-errors
      summary: List error details
      tags:
      - Errors
      description: |
        Returns a list of image or video errors for the transformations requested in the past three days.
      parameters:
      - $ref: parameters/details-limit-query.yaml
      - $ref: parameters/details-url-query.yaml
      - $ref: parameters/details-policy-id-query.yaml
      - $ref: parameters/details-size-query.yaml
      - $ref: parameters/details-transformation-type-query.yaml
      responses:
        200:
          description: |
            The request was successful.
          content:
            application/json:
              example:
                $ref: examples/details-error-array.json
              schema:
                $ref: schemas/details-error-array.yaml
  /network/{network}/details/logs:
    parameters:
    - $ref: parameters/network-path.yaml
    get:
      operationId: get-logs
      summary: List log details
      tags:
      - Logs
      description: |
        Returns a list of image or video logs for the transformations requested in the past three days.
      parameters:
      - $ref: parameters/contract-id-header.yaml
      - $ref: parameters/policy-set-id-header.yaml
      - $ref: parameters/details-limit-query.yaml
      - $ref: parameters/details-url-query.yaml
      - $ref: parameters/details-policy-id-query.yaml
      - $ref: parameters/details-size-query.yaml
      - $ref: parameters/details-transformation-type-query.yaml
      responses:
        200:
          description: |
            The request was successful.
          content:
            application/json:
              example:
                $ref: examples/details-log-array.json
              schema:
                $ref: schemas/details-log-array.yaml
