openapi: 3.0.0
info:
  title: Invoices
  version: v1
servers:
- url: https://{hostname}/invoicing-api/v3
tags:
- description: Get invoice and credit memo data for a contract.
  name: Invoices
x-akamai:
  auth-type: EDGE_GRID
paths:
  /contracts/{contractId}/invoices:
    $ref: paths/invoices-contract.yaml
  /contracts/{contractId}/invoices/{invoiceId}/download:
    $ref: paths/download.yaml
  /invoices:
    $ref: paths/invoices.yaml
