openapi: 3.0.0
info:
  title: Notifications
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/invoicing-api/v3
tags:
- description: Manage who receives notifications when new invoices or credit memos
    are available.
  name: Notifications
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-notifications.yaml
paths:
  /notifications:
    $ref: paths/notifications.yaml
  /notifications/{notificationId}:
    $ref: paths/notification.yaml
