openapi: 3.0.0
info:
  title: Network Lists
  version: '2'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/network-list/v2
tags:
- description: Manage your network lists. Network lists are shared sets of IP addresses,
    CIDR blocks, or broad geographic areas.
  name: Network lists
- description: Manage the settings, or elements, within a network list.
  name: Elements
- description: Manage network list activations.
  name: Activations
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-network-lists.yaml
paths:
  /network-lists:
    $ref: paths/network-lists.yaml
  /network-lists/{networkListId}:
    $ref: paths/network-list.yaml
  /network-lists/{networkListId}/append:
    $ref: paths/append.yaml
  /network-lists/{networkListId}/details:
    $ref: paths/details.yaml
  /network-lists/{networkListId}/elements:
    $ref: paths/elements.yaml
  /network-lists/{networkListId}/environments/{environment}/activate:
    $ref: paths/activate.yaml
  /network-lists/{networkListId}/environments/{environment}/status:
    $ref: paths/status.yaml
  /network-lists/{networkListId}/sync-points/{syncPoint}/history:
    $ref: paths/history.yaml
