openapi: 3.0.0
info:
  title: Activations
  version: '2'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/network-list/v2
tags:
- description: Manage network list activations.
  name: Activations
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-activations.yaml
paths:
  /activations/{activationId}:
    $ref: paths/activation.yaml
