openapi: 3.0.0
info:
  title: Notifications
  version: '2'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/network-list/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-notifications.yaml
paths:
  /notifications/subscribe:
    $ref: paths/subscribe.yaml
  /notifications/unsubscribe:
    $ref: paths/unsubscribe.yaml
