openapi: 3.0.0
info:
  title: Maps
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/siteshield/v1
tags:
- description: Manage your Site Shield maps.
  name: Maps
x-akamai:
  auth-type: EDGE_GRID
  file-path: site-shield.yaml
paths:
  /maps:
    $ref: paths/maps.yaml
  /maps/{id}:
    $ref: paths/id.yaml
  /maps/{id}/acknowledge:
    $ref: paths/acknowledge.yaml
