openapi: 3.0.0
info:
  title: Email enrollments
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/amfa/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-email-enrollments.yaml
paths:
  /email-enrollments:
    $ref: paths/email-enrollments.yaml
