openapi: 3.0.0
info:
  title: Users
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/amfa/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-users.yaml
paths:
  /users:
    $ref: paths/users.yaml
  /users/{userId}:
    $ref: paths/user.yaml
  /users/{userId}/aliases:
    $ref: paths/aliases.yaml
  /users/{userId}/aliases/{userAliasId}:
    $ref: paths/user-alias.yaml
  /users/{userId}/assign-groups:
    $ref: paths/assign-groups.yaml
  /users/{userId}/assign-policies:
    $ref: paths/assign-policies.yaml
  /users/{userId}/bypass-codes:
    $ref: paths/bypass-codes.yaml
  /users/{userId}/bypass-codes/{bypassCodeId}:
    $ref: paths/bypass-code.yaml
  /users/{userId}/devices:
    $ref: paths/devices.yaml
  /users/{userId}/devices/assign-hardware-token:
    $ref: paths/assign-hardware-token.yaml
  /users/{userId}/devices/{deviceId}/disable:
    $ref: paths/disable.yaml
  /users/{userId}/devices/{deviceId}/enable:
    $ref: paths/enable.yaml
