openapi: 3.0.0
info:
  title: Groups
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/amfa/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-groups.yaml
paths:
  /groups:
    $ref: paths/groups.yaml
  /groups/{groupId}:
    $ref: paths/group.yaml
  /groups/{groupId}/users/{userId}:
    $ref: paths/user-per-group.yaml
