openapi: 3.0.0
info:
  title: Bulk zones
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/config-dns/v2
tags:
- description: Groups operations that you can use to manage zone creation requests.
  name: Create requests
- description: Groups operations that you can use to manage zone deletion requests.
  name: Delete requests
x-akamai:
  auth-type: EDGE_GRID
  file-path: 08-bulk-operations.yaml
paths:
  /proxies/{proxyId}/zones/create-requests:
    $ref: paths/proxy-create-requests.yaml
  /proxies/{proxyId}/zones/create-requests/{requestId}:
    $ref: paths/proxy-create-request.yaml
  /proxies/{proxyId}/zones/create-requests/{requestId}/result:
    $ref: paths/proxy-create-result.yaml
  /proxies/{proxyId}/zones/delete-requests:
    $ref: paths/proxy-delete-requests.yaml
  /proxies/{proxyId}/zones/delete-requests/results:
    $ref: paths/proxy-delete-results.yaml
  /proxies/{proxyId}/zones/delete-requests/{requestId}:
    $ref: paths/proxy-delete-request.yaml
  /proxies/{proxyId}/zones/delete-requests/{requestId}/result:
    $ref: paths/proxy-delete-result.yaml
  /zones/create-requests:
    $ref: paths/zone-create-requests.yaml
  /zones/create-requests/{requestId}:
    $ref: paths/zone-create-request.yaml
  /zones/create-requests/{requestId}/result:
    $ref: paths/zone-create-result.yaml
  /zones/delete-requests:
    $ref: paths/zone-delete-requests.yaml
  /zones/delete-requests/{requestId}:
    $ref: paths/zone-delete-request.yaml
  /zones/delete-requests/{requestId}/result:
    $ref: paths/zone-delete-result.yaml
