openapi: 3.0.0
info:
  title: Bulk Zone Operations
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/config-dns/v2
tags:
- description: Groups operations that you can use to manage zone creation requests.
  name: Create requests
- description: Groups operations that you can use to manage zone deletion requests.
  name: Delete requests
x-akamai:
  auth-type: EDGE_GRID
  file-path: bulk-operations.yaml
paths:
  /proxies/{proxyId}/zones/create-requests:
    parameters:
    - $ref: parameters/proxyId-path.yaml
    - $ref: parameters/pageable_page.yaml
    - $ref: parameters/pageable_pageSize.yaml
    - $ref: parameters/pageable_showAll.yaml
    - $ref: parameters/is-complete-query.yaml
    - $ref: parameters/is-expired-query.yaml
    post:
      operationId: post-proxy-zones-create-requests
      summary: Submit a bulk proxy zone create request
      tags:
      - Create requests
      description: |
        Submits a request to create one or more new Proxy Zones asynchronously. The request body contains a JSON array. Each object in the array contains the data necessary to create a proxy zone. All proxy zones are created on the same contract and group.  An offline task creates the new proxy zones. You can use the response's `requestId` to check the task's status and view its results once it completes.
      parameters:
      - $ref: parameters/proxyId-path.yaml
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/create-proxy-request-post-request.json
            schema:
              $ref: schemas/create-proxy-request-post.yaml
      responses:
        201:
          description: |
            Resource successfully created.
          headers:
            Location:
              $ref: headers/Location.yaml
          content:
            application/json:
              example:
                $ref: examples/async-request-post-response.json
              schema:
                $ref: schemas/async-request-id.yaml
    get:
      operationId: get-proxy-zones-create-requests-result
      summary: Get a bulk proxy zone create results for a proxy
      tags:
      - Create requests
      description: |
        Retrieves the results of requests for a given proxy.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/async-proxy-request-status-get.json
              schema:
                $ref: schemas/get-proxy-zone-requests-response.yaml
  /proxies/{proxyId}/zones/create-requests/{requestId}:
    parameters:
    - $ref: parameters/proxyId-path.yaml
    - $ref: parameters/requestId-create-path.yaml
    get:
      operationId: get-proxy-zones-create-requests-requestid
      summary: Check bulk proxy zone create status
      tags:
      - Create requests
      description: |
        Retrieves the current status of a running or completed request. The `requestId` was returned when the create request was initiated.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/async-request-status-get.json
              schema:
                $ref: schemas/async-request-status.yaml
  /proxies/{proxyId}/zones/create-requests/{requestId}/result:
    parameters:
    - $ref: parameters/proxyId-path.yaml
    - $ref: parameters/requestId-create-path.yaml
    get:
      operationId: get-proxy-zones-create-requests-requestid-result
      summary: Get a bulk proxy zone create result
      tags:
      - Create requests
      description: |
        Retrieves the results from a completed request.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/create-proxy-request-get-response.json
              schema:
                $ref: schemas/create-proxy-request-result.yaml
  /proxies/{proxyId}/zones/delete-requests:
    post:
      operationId: post-proxy-zones-delete-requests
      summary: Submit a bulk proxy zone delete request
      tags:
      - Delete requests
      description: |
        Submits a request to delete one or more proxy zones asynchronously. Each element in the response array is the name of a proxy zone to be deleted.  Before deleting a zone from the Edge DNS system, the API makes sure Akamai servers aren't receiving DNS requests for that proxy zone. It also checks that the proxy zone isn't currently delegated to Akamai's name servers.  An offline task deletes the proxy zones. The result of this operation is a `requestId`, which you can use to check the task's status and view its results once it completes.
      parameters:
      - $ref: parameters/proxyId-path.yaml
      - $ref: parameters/bypassSafetyChecks-query.yaml
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/proxy-zone-name-list.json
            schema:
              $ref: schemas/proxy-zone-name-list.yaml
      responses:
        201:
          description: |
            Successful operation.
          headers:
            Location:
              $ref: headers/Location.yaml
          content:
            application/json:
              example:
                $ref: examples/async-request-post-response.json
              schema:
                $ref: schemas/async-request-id.yaml
  /proxies/{proxyId}/zones/delete-requests/results:
    parameters:
    - $ref: parameters/proxyId-path.yaml
    - $ref: parameters/pageable_page.yaml
    - $ref: parameters/pageable_pageSize.yaml
    - $ref: parameters/pageable_showAll.yaml
    - $ref: parameters/is-complete-query.yaml
    get:
      operationId: get-proxy-zones-delete-requests-result
      summary: Get all bulk proxy zone delete results
      tags:
      - Delete requests
      description: |
        Retrieves the results for all requests for a given proxy.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/async-proxy-request-status-get.json
              schema:
                $ref: schemas/get-proxy-zone-requests-response.yaml
  /proxies/{proxyId}/zones/delete-requests/{requestId}:
    parameters:
    - $ref: parameters/proxyId-path.yaml
    - $ref: parameters/requestId-create-path.yaml
    get:
      operationId: get-proxy-zones-delete-requests-requestid
      summary: Check bulk proxy zone delete status
      tags:
      - Delete requests
      description: |
        Retrieves the current status of a running or completed request. The `requestId` was returned when the delete request was initiated.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/async-request-status-get.json
              schema:
                $ref: schemas/async-request-status.yaml
  /proxies/{proxyId}/zones/delete-requests/{requestId}/result:
    parameters:
    - $ref: parameters/proxyId-path.yaml
    - $ref: parameters/requestId-create-path.yaml
    get:
      operationId: get-proxy-zones-delete-requests-requestid-result
      summary: Get a bulk proxy zone delete result
      tags:
      - Delete requests
      description: |
        Retrieves the result from a completed request.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/delete-proxy-request-get-response.json
              schema:
                $ref: schemas/delete-proxy-request-result.yaml
  /zones/create-requests:
    post:
      operationId: post-zones-create-requests
      summary: Submit a bulk zone create request
      tags:
      - Create requests
      description: |
        Submits a request to create one or more new Zones asynchronously. The request body contains a JSON array. Each object in the array contains the data necessary to create a zone. All zones are created on the same contract and group.  An offline task creates the new zones. You can use the response's `requestId` to check the task's status and view its results once it completes.
      parameters:
      - $ref: parameters/contractId-query.yaml
      - $ref: parameters/groupAware_gid.yaml
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/create-request-post-request.json
            schema:
              $ref: schemas/create-request-post.yaml
      responses:
        201:
          description: |
            Resource successfully created.
          headers:
            Location:
              $ref: headers/Location.yaml
          content:
            application/json:
              example:
                $ref: examples/async-request-post-response.json
              schema:
                $ref: schemas/async-request-id.yaml
  /zones/create-requests/{requestId}:
    parameters:
    - $ref: parameters/requestId-create-path.yaml
    get:
      operationId: get-zones-create-requests-requestid
      summary: Check bulk zone create status
      tags:
      - Create requests
      description: |
        Retrieves the current status of a running or completed request. The `requestId` was returned when the create request was initiated.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/async-request-status-get.json
              schema:
                $ref: schemas/async-request-status.yaml
  /zones/create-requests/{requestId}/result:
    parameters:
    - $ref: parameters/requestId-create-path.yaml
    get:
      operationId: get-zones-create-requests-requestid-result
      summary: Get bulk zone create results
      tags:
      - Create requests
      description: |
        Retrieves the results from a completed request.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/create-request-result-get.json
              schema:
                $ref: schemas/create-request-result.yaml
  /zones/delete-requests:
    post:
      operationId: post-zones-delete-requests
      summary: Submit a bulk zone delete request
      tags:
      - Delete requests
      description: |
        Submits a request to delete one or more new Zones asynchronously. The request body contains a JSON array. Each element in the array is the name of a zone to be deleted.  Before deleting a zone from the Edge DNS system, the API makes sure Akamai servers aren't receiving DNS requests for that zone. It also checks that the zone isn't currently delegated to Akamai's name servers.  An offline task deletes the new zones. The result of this operation is a `requestId`, which you can use to check the task's status and view its results once it completes.
      parameters:
      - $ref: parameters/bypassSafetyChecks-query.yaml
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/zone-name-list.json
            schema:
              $ref: schemas/zone-name-list.yaml
      responses:
        201:
          description: |
            Successful operation.
          headers:
            Location:
              $ref: headers/Location.yaml
          content:
            application/json:
              example:
                $ref: examples/async-request-post-response.json
              schema:
                $ref: schemas/async-request-id.yaml
  /zones/delete-requests/{requestId}:
    parameters:
    - $ref: parameters/requestId-delete-path.yaml
    get:
      operationId: get-zones-delete-requests-requestid
      summary: Check bulk zone delete status
      tags:
      - Delete requests
      description: |
        Retrieves the current status of a running or completed request. The `requestId` was returned when the delete request was initiated.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/async-request-status-get.json
              schema:
                $ref: schemas/async-request-status.yaml
  /zones/delete-requests/{requestId}/result:
    parameters:
    - $ref: parameters/requestId-delete-path.yaml
    get:
      operationId: get-zones-delete-requests-requestid-result
      summary: Get bulk zone delete results
      tags:
      - Delete requests
      description: |
        Retrieves the `results` from a completed request.
      responses:
        200:
          description: |
            Successful operation.
          content:
            application/json:
              example:
                $ref: examples/delete-request-result-get.json
              schema:
                $ref: schemas/delete-request-result.yaml
