type: object
x-akamai:
  file-path: schemas/SettingSingle.yaml
properties:
  configVersions:
    type: array
    items:
      type: integer
  createdBy:
    type: string
  createdTimestamp:
    type: string
    format: date-time
  pdId:
    type: integer
  policyDomainName:
    type: string
  portsLimit:
    type: integer
  updatedBy:
    type: string
    nullable: true
  updatedTimestamp:
    type: string
    format: date-time
  vipsLimit:
    type: integer
