name: configDeploymentId
in: path
description: |-
  A unique ID for the configuration deployment.
  
x-akamai:
  file-path: parameters/config-deployment-id-path.yaml
required: true
schema:
  type: integer
  example: 101
