name: deploymentStatuses
in: query
description: |
  The deployment status to query. You can provide several comma-separated values.
explode: false
style: form
required: false
schema:
  type: string
  example: COMPLETED
  enum:
  - CONTENT_EXTERNAL
  - REVERTING
  - STAGING
  - PENDING
  - RUNNING
  - COMPLETED
  - FAILED
  - BUILDING
  - ABORTED
  - AUTO_RKS_ONLY
