openapi: 3.0.0
info:
  title: MSL Ingest
  version: '2'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/config-media-live/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: msl-origin.yaml
paths:
  /msl-origin/cdns:
    $ref: paths/cdns.yaml
  /msl-origin/contracts:
    $ref: paths/contracts.yaml
  /msl-origin/cpcodes:
    $ref: paths/cpcodes.yaml
  /msl-origin/generate-key:
    $ref: paths/generate-key.yaml
  /msl-origin/origins:
    $ref: paths/origins.yaml
  /msl-origin/origins/cpcodes:
    $ref: paths/origins-cpcodes.yaml
  /msl-origin/origins/{originId}:
    $ref: paths/origin.yaml
  /msl-origin/publishing-locations:
    $ref: paths/publishing-locations.yaml
  /msl-origin/streams:
    $ref: paths/streams.yaml
  /msl-origin/streams/{streamId}:
    $ref: paths/stream.yaml
  /msl-origin/vod-origin:
    $ref: paths/vod-origin.yaml
