openapi: 3.0.0
info:
  title: Agent groups
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/sla-api/v1
tags:
- description: Groups operations that you can use to get details of agent groups.
  name: Agent groups
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-agent-groups.yaml
paths:
  /agent-groups:
    $ref: paths/agent-groups.yaml
