openapi: 3.0.0
info:
  title: Test quotas
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/sla-api/v1
tags:
- description: Groups operations that you can use to get details of contract quotas.
  name: Quotas
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-test-quotas.yaml
paths:
  /test-quotas:
    $ref: paths/test-quotas.yaml
