openapi: 3.0.0
info:
  title: Test quotas
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/sla-api/v1
tags:
- description: Groups operations that you can use to get details of contract quotas.
  name: Quotas
x-akamai:
  auth-type: EDGE_GRID
  file-path: test-quotas.yaml
paths:
  /test-quotas:
    get:
      operationId: get-quotas
      summary: List test configuration quotas
      tags:
      - Quotas
      description: |
        Each contract has a maximum number of allowed test configurations. Get the test quotas to find out how many test configurations are allowed and how many are in use.
      responses:
        200:
          description: |
            OK.
          content:
            application/json:
              example:
                $ref: examples/get-quotas-200.json
              schema:
                $ref: schemas/schema-get-quotas-200.yaml
