openapi: 3.0.0
info:
  title: Reports
  version: v2
servers:
- url: https://{hostname}/reporting-api/v2
tags:
- description: Get information about the different kinds of reports available.
  name: Report list
- description: Get available options to generate a report.
  name: Report metadata
- description: Run reports to get data about your Akamai services.
  name: Report data
x-akamai:
  auth-type: EDGE_GRID
paths:
  /reports:
    $ref: paths/reports.yaml
  /reports/{productFamily}:
    $ref: paths/product-family.yaml
  /reports/{productFamily}/{reportingArea}:
    $ref: paths/reporting-area.yaml
  /reports/{productFamily}/{reportingArea}/{report}:
    $ref: paths/report.yaml
  /reports/{productFamily}/{reportingArea}/{report}/data:
    $ref: paths/report-data.yaml
  /reports/{productFamily}/{reportingArea}/{report}/queries/{queryId}:
    $ref: paths/query.yaml
