type: object
description: |
  Lists client config update properties.
additionalProperties: false
required:
- clientIdentityReporting
- downgradeEnable
- endUserControl
- entitlementCode
- forwardDnsTraffic
- httpProxyOverride
- httpProxyPort
- securityPatchAutoUpgrade
- uninstallEnable
properties:
  clientIdentityReporting:
    type: boolean
    description: |
      Enables client identity reporting.
  downgradeEnable:
    type: boolean
    description: |
      Enables client downgrade.
  endUserControl:
    type: boolean
    description: |
      Enables end user control.
  entitlementCode:
    type: string
    description: |
      The entitlement code in encoded format.
    minLength: 1
  forwardDnsTraffic:
    type: boolean
    description: |
      Enables DNS traffic forwarding.
  httpProxyOverride:
    type: integer
    description: |
      The HTTP proxy override units.
    minimum: 0
  httpProxyPort:
    type: integer
    description: |
      The proxy port of the client.
    minimum: 1
  securityPatchAutoUpgrade:
    type: boolean
    description: |
      Enables security patch auto upgrade.
  uninstallEnable:
    type: boolean
    description: |
      Enables uninstall.
