type: object
description: |
  The set of deployed sites, policies, lists, and custom responses.
additionalProperties: false
required:
- sites
- subLocations
- policies
- honeypots
- customlists
- customPatterns
properties:
  sites:
    type: array
    description: |
      List of site IDs in the deployment.
    minItems: 0
    items:
      $ref: resourceIdOnly.yaml
  subLocations:
    type: array
    description: |
      List of sublocation IDs in the deployment.
    minItems: 0
    items:
      $ref: resourceIdOnly.yaml
  policies:
    type: array
    description: |
      List of policy IDs in the deployment.
    minItems: 0
    items:
      $ref: resourceIdOnly.yaml
  honeypots:
    type: array
    description: |
      List of custom response IDs in the deployment.
    minItems: 0
    items:
      $ref: resourceIdOnly.yaml
  customlists:
    type: array
    description: |
      The set of custom list IDs in the deployment.
    minItems: 0
    items:
      $ref: resourceIdOnly.yaml
  customPatterns:
    type: array
    description: |
      The set of custom dictionary patterns in the deployment.
    minItems: 0
    items:
      $ref: resourceIdOnly.yaml
  globalSettings:
    type: object
    description: |
      The global settings updated for the deployment. 
    additionalProperties: false
    properties:
      id:
        type: integer
        description: |
          The unique ID for the global settings modified.
        minimum: 0
  whitelists:
    type: array
    description: |
      The allowlists removed from the deployment. 
    minItems: 0
    items:
      type: string
      minLength: 1
  blacklists:
    type: array
    description: |
      The blocklists removed from the deployment. 
    minItems: 0
    items:
      type: string
      minLength: 1
