type: object
description: |
  Contains deployment change details.
additionalProperties: false
required:
- changes
properties:
  changes:
    type: array
    description: |
      Deployment change details.
    minItems: 0
    items:
      type: object
      additionalProperties: false
      required:
      - deltaType
      - changes
      properties:
        deltaType:
          type: string
          description: |
            Name of entity type changed. Either `sites`, `policies`, `lists`, `subLocations`, `customLists`, or `global_settings`.
          enum:
          - sites
          - policies
          - lists
          - subLocations
          - customLists
          - global_settings
        changes:
          type: array
          description: |
            Lists deployment changes.
          minItems: 0
          items:
            type: object
            additionalProperties: false
            required:
            - changeType
            - detail
            - changes
            properties:
              changeType:
                type: string
                description: |
                  The type of change, either `Created`, `Modified`, `Added`, or `Removed`.
                enum:
                - Created
                - Modified
                - Added
                - Removed
              detail:
                type: object
                description: |
                  Describes the change details.
                additionalProperties: false
                required:
                - name
                properties:
                  id:
                    type: integer
                    description: |
                      A unique identifier for the change.
                    minimum: 1
                  name:
                    type: string
                    description: |
                      Name of the change.
                    minLength: 1
                  modifiedBy:
                    type: string
                    description: |
                      User who made the modification.
                    readOnly: true
                    minLength: 1
                  modifiedDate:
                    type: string
                    description: |
                      Date of entity modification.
                    readOnly: true
                    format: date-time
              changes:
                type: array
                description: |
                  Nested deployment diff objects.
                minItems: 0
                items:
                  type: object
                  additionalProperties: false
                  required:
                  - changeType
                  - detail
                  - changes
                  properties:
                    changeType:
                      type: string
                      description: |
                        The type of change, either `Created`, `Modified`, `Added`, or `Removed`.
                      enum:
                      - Created
                      - Modified
                      - Added
                      - Removed
                      minLength: 1
                    detail:
                      type: object
                      description: |
                        Describes the change details.
                      additionalProperties: false
                      required:
                      - name
                      properties:
                        id:
                          type: integer
                          description: |
                            Unique identifier for the change.
                          minimum: 1
                        name:
                          type: string
                          description: |
                            Name of the change.
                          minLength: 1
                        modifiedBy:
                          type: string
                          description: |
                            User who made the change.
                          minLength: 1
                        modifiedDate:
                          type: string
                          description: |
                            When the change occurred.
                          readOnly: true
                          format: date-time
                        oldValue:
                          type: string
                          description: |
                            The value before the change. 
                          minLength: 0
                        newValue:
                          type: string
                          description: |
                            The value after the change.
                          minLength: 0
                    changes:
                      type: array
                      description: |
                        Nested deployment diff objects.
                      minItems: 0
                      items:
                        type: object
                        additionalProperties: false
                        required:
                        - changeType
                        - detail
                        properties:
                          changeType:
                            type: string
                            description: |
                              The type of change, either `Created`, `Modified`, `Added`, or `Removed`.
                            enum:
                            - Created
                            - Modified
                            - Added
                            - Removed
                            minLength: 1
                          detail:
                            type: object
                            description: |
                              Describes the change details.
                            additionalProperties: false
                            required:
                            - name
                            properties:
                              id:
                                type: integer
                                description: |
                                  Unique identifier for the change.
                                minimum: 1
                              name:
                                type: string
                                description: |
                                  Name of the change.
                                minLength: 1
                              modifiedBy:
                                type: string
                                description: |
                                  User who made the change.
                                readOnly: true
                                minLength: 1
                              modifiedDate:
                                type: string
                                description: |
                                  When the change occurred.
                                readOnly: true
                                format: date-time
                              oldValue:
                                type: string
                                description: |
                                  The value before the change. 
                                minLength: 0
                              newValue:
                                type: string
                                description: |
                                  The value after the change.
                                minLength: 0
