type: object
description: |
  Deployment details.
additionalProperties: false
required:
- id
- status
- message
- comment
- startTime
- deployedBy
- progressPct
properties:
  id:
    type: integer
    description: |
      Unique identifier of the deployment.
    minimum: 1
  status:
    type: string
    description: |
      Specifies the deployment status. Either `CONTENT_EXTERNAL`, `REVERTING`, `STAGING`, `PENDING`, `RUNNING`, `COMPLETED`, `FAILED`, `BUILDING`, or `AUTO_RKS_ONLY`.
    enum:
    - CONTENT_EXTERNAL
    - REVERTING
    - STAGING
    - PENDING
    - RUNNING
    - COMPLETED
    - FAILED
    - BUILDING
    - AUTO_RKS_ONLY
  message:
    type: string
    description: |
      Deployment details.
    minLength: 1
  comment:
    type: string
    description: |
      User comment provided for deployment.
    minLength: 1
  startTime:
    type: string
    description: |
      Start time of deployment.
    readOnly: true
    format: date-time
  endTime:
    type: string
    description: |
      Time of deployment completion.
    readOnly: true
    format: date-time
  deployedBy:
    type: string
    description: |
      User who initiated the deployment.
    readOnly: true
    minLength: 1
  progressPct:
    type: integer
    description: |
      Indicates the deployment progress in percentage.
    minimum: 0
    maximum: 100
