type: object
description: |-
  The set of deployed sites, policies, lists, and custom responses.
  
x-akamai:
  file-path: schemas/deployment-post-crud-section.yaml
additionalProperties: false
required:
- sites
- subLocations
- policies
- honeypots
- customlists
- customPatterns
properties:
  blacklists:
    type: array
    description: |
      The blocklists removed from the deployment.
    minItems: 0
    items:
      type: string
      minLength: 1
  customPatterns:
    type: array
    description: |
      The set of custom dictionary patterns in the deployment.
    minItems: 0
    items:
      $ref: resource-id-only.yaml
  customlists:
    type: array
    description: |
      The set of custom list IDs in the deployment.
    minItems: 0
    items:
      $ref: resource-id-only.yaml
  globalSettings:
    type: object
    description: |
      The global settings updated for the deployment.
    additionalProperties: false
    properties:
      id:
        type: integer
        description: |
          The unique ID for the global settings modified.
        minimum: 0
  honeypots:
    type: array
    description: |
      List of custom response IDs in the deployment.
    minItems: 0
    items:
      $ref: resource-id-only.yaml
  policies:
    type: array
    description: |
      List of policy IDs in the deployment.
    minItems: 0
    items:
      $ref: resource-id-only.yaml
  sites:
    type: array
    description: |
      List of site IDs in the deployment.
    minItems: 0
    items:
      $ref: resource-id-only.yaml
  subLocations:
    type: array
    description: |
      List of sublocation IDs in the deployment.
    minItems: 0
    items:
      $ref: resource-id-only.yaml
  whitelists:
    type: array
    description: |
      The allowlists removed from the deployment.
    minItems: 0
    items:
      type: string
      minLength: 1
