type: object
description: |
  Lists the file type setting parameters.
additionalProperties: false
required:
- name
- type
- responseId
- fileTypeId
- users
- groups
- responseInfo
- responseOverrides
- fileTypeInfo
- applyTo
properties:
  name:
    type: string
    description: |
      Name of the file type.
    minLength: 1
  type:
    type: string
    description: |
      Lists the file type.
    minLength: 1
  responseId:
    type: integer
    description: |
      Lists the response ID for the file type setting.
    readOnly: true
    minimum: 1
  fileTypeId:
    type: integer
    description: |
      Identifies each file type.
    readOnly: true
    minimum: 1
  users:
    type: array
    description: |
      Specifies user emails assigned to the policy.
    minItems: 0
    items:
      type: string
      minLength: 1
  groups:
    type: array
    description: |
      List of groups that users belong to.
    minItems: 0
    items:
      type: string
      minLength: 1
  responseInfo:
    description: |
      Provides details about response.
    $ref: response-info.yaml
  responseOverrides:
    type: array
    description: |
      Contains the AVC response override details.
    minItems: 0
    items:
      $ref: response-override.yaml
  fileTypeInfo:
    $ref: file-type-info.yaml
  applyTo:
    type: string
    description: |
      Lists policies to apply the file type settings to.
    minLength: 1
