type: object
description: |
  Provides global settings details.
additionalProperties: false
required:
- blockRoamingTraffic
properties:
  globalSettingsId:
    type: integer
    description: |
      Unique ID of the global setting.
    minimum: 1
  enableSourceIpBind:
    type: boolean
    description: |
      Enables source IP binding.
  sourceIpBindCidrs:
    type: array
    description: |
      List of IP CIDRs available for `sourceIpBind`.
    minItems: 0
    items:
      type: string
      minLength: 1
  blockRoamingTraffic:
    type: boolean
    description: |
      Blocks roaming traffic.
  quicklistMigrated:
    type: boolean
    description: |
      Migrates the quicklist.
  createdBy:
    type: string
    description: |
      Name of the user who created this global setting.
    minLength: 1
  createdDate:
    type: string
    description: |
      ISO 8601 timestamp this global setting's creation.
    readOnly: true
    format: date-time
  modifiedBy:
    type: string
    description: |
      The user who modified this global setting.
    minLength: 1
  modifiedDate:
    type: string
    description: |
      ISO 8601 timestamp marking this global setting's last modification.
    readOnly: true
    format: date-time
  enableChinaRegion:
    type: boolean
    description: |
      Enables the China region for the deployment.
  chinaDeploymentStatus:
    type: string
    description: |
      The status of the China region deployment.
      Possible values are: `STAGING`, `PENDING`, `BUILDING`, `RUNNING`, `COMPLETED`, `CONTENT_EXTERNAL`, `REVERTING`, `FAILED`, or `ABORTED`.
    enum:
    - STAGING
    - PENDING
    - BUILDING
    - RUNNING
    - COMPLETED
    - CONTENT_EXTERNAL
    - REVERTING
    - FAILED
    - ABORTED
  asnExceptions:
    type: array
    description: |
      List of AS number exceptions.
    minItems: 0
    uniqueItems: true
    items:
      type: integer
      description: |
        AS number.
      minimum: 1
      maximum: 4294967294
