openapi: 3.0.0
info:
  title: Invoices
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/invoicing-api/v3
tags:
- description: Get invoice and credit memo data for a contract.
  name: Invoices
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-invoices.yaml
paths:
  /contracts/{contractId}/invoices:
    $ref: paths/invoices-contract.yaml
  /contracts/{contractId}/invoices/{invoiceId}/download:
    $ref: paths/download.yaml
  /invoices:
    $ref: paths/invoices.yaml
