openapi: 3.0.0
info:
  title: Invoices
  version: v4
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/invoicing-api/v4
tags:
- description: Get invoice and credit memo data for a contract.
  name: Invoices
x-akamai:
  auth-type: EDGE_GRID
  file-path: invoices.yaml
paths:
  /contracts/{contractId}/invoices:
    parameters:
    - $ref: parameters/contractId-path.yaml
    get:
      operationId: get-contracts-invoices
      summary: List invoices and credit memos for a contract
      tags:
      - Invoices
      description: |
        Returns invoices and credit memos for the specified contract and the selected month.
      parameters:
      - $ref: parameters/monthQueryParam_month.yaml
      responses:
        200:
          description: |
            The response lists invoices and credit memos.
          content:
            application/json:
              example:
                $ref: examples/list-invoices-200.json
              schema:
                $ref: schemas/list-invoices-schema.yaml
        204:
          description: |
            No content. No data to be returned for the requested parameters.
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        404:
          $ref: errors/404.yaml
        405:
          $ref: errors/405.yaml
        500:
          $ref: errors/500.yaml
  /contracts/{contractId}/invoices/{invoiceId}/download:
    parameters:
    - $ref: parameters/invoiceId-path.yaml
    - $ref: parameters/contractId-path.yaml
    get:
      operationId: get-contract-invoice-download
      summary: Download an invoice or a credit memo file
      tags:
      - Invoices
      description: |
        Returns the content of the selected contract's invoice, credit memo file, or usage data for Cloud Computing services. The downloadable file is available in the response body. The format of the file depends on the value of the `Accept` header. Available formats are `CSV`, `PDF`, and `JSON`. 
      parameters:
      - $ref: parameters/sourceType-query.yaml
      responses:
        200:
          description: |
            The response provides requested file.
          content:
            application/json:
              schema:
                type: object
                example:
                  $ref: examples/invoice-download-200.json
                additionalProperties: true
            application/pdf:
              schema:
                type: string
                format: binary
            text/csv:
              schema:
                type: string
                example:
                  $ref: examples/invoice-download-200.csv
        204:
          description: |
            No content. No data to be returned for the requested parameters.
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        404:
          $ref: errors/404.yaml
        405:
          $ref: errors/405.yaml
        500:
          $ref: errors/500.yaml
  /invoices:
    get:
      operationId: get-invoices
      summary: List invoices and credit memos for an account
      tags:
      - Invoices
      description: |
        Returns invoices and credit memos for the current account and the selected month.
      parameters:
      - $ref: parameters/monthQueryParam_month.yaml
      responses:
        200:
          description: |
            The response lists invoices and credit memos.
          content:
            application/json:
              example:
                $ref: examples/list-invoices-200.json
              schema:
                $ref: schemas/list-invoices-schema.yaml
        204:
          description: |
            No content. No data to be returned for the requested parameters.
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        404:
          $ref: errors/404.yaml
        405:
          $ref: errors/405.yaml
        500:
          $ref: errors/500.yaml
