type: object
description: |-
  BGP config summary read schema.
  
x-akamai:
  file-path: schemas/bgp-config.read-summary.yaml
additionalProperties: false
required:
- name
- bgpConfigId
properties:
  name:
    $ref: mapping.definitions.schema.yaml#/definitions/nameType
  bgpConfigId:
    $ref: bgp-config.definitions.schema.yaml#/definitions/bgpConfigIdType
