description: |-
  BGP configuration property definitions.
  
x-akamai:
  file-path: schemas/bgp-config.definitions.schema.yaml
definitions:
  bgpConfigIdType:
    type: integer
    description: |
      The unique identifier for a BGP configuration.
    minimum: 1
