type: object
description: |-
  BGP config collection.
  
x-akamai:
  file-path: schemas/bgp-config.collection.yaml
additionalProperties: false
required:
- bgpConfigs
- page
properties:
  bgpConfigs:
    type: array
    description: |
      TBD. A page of BgpConfig objects matching the specified filtering and sorting criteria.
    items:
      $ref: bgp-config.read-summary.yaml
  page:
    $ref: definitions.yaml#/definitions/pageType
