type: object
description: |-
  BGP config update schema.
  
x-akamai:
  file-path: schemas/bgp-config.update.yaml
additionalProperties: false
required:
- name
- bgpConfigId
properties:
  name:
    $ref: mapping.definitions.schema.yaml#/definitions/nameType
  description:
    $ref: mapping.definitions.schema.yaml#/definitions/descriptionType
  bgpConfigId:
    $ref: bgp-config.definitions.schema.yaml#/definitions/bgpConfigIdType
