type: object
description: |-
  BGP config create schema.
  
x-akamai:
  file-path: schemas/bgp-config.create.yaml
additionalProperties: false
required:
- name
properties:
  name:
    $ref: mapping.definitions.schema.yaml#/definitions/nameType
  description:
    $ref: mapping.definitions.schema.yaml#/definitions/descriptionType
