type: object
description: |-
  BGP configuration object descriptions.
  
x-akamai:
  file-path: schemas/bgp-config.read-detailed.yaml
additionalProperties: false
required:
- name
- bgpConfigId
properties:
  name:
    $ref: mapping.definitions.schema.yaml#/definitions/nameType
  description:
    $ref: mapping.definitions.schema.yaml#/definitions/descriptionType
  bgpConfigId:
    readOnly: true
    $ref: bgp-config.definitions.schema.yaml#/definitions/bgpConfigIdType
  dateCreated:
    $ref: mapping.definitions.schema.yaml#/definitions/dateCreatedType
  lastUpdated:
    $ref: mapping.definitions.schema.yaml#/definitions/lastUpdatedType
