type: object
x-akamai:
  file-path: schemas/bgp-config-multipart.yaml
additionalProperties: false
required:
- metadata
- config
properties:
  config:
    type: string
    description: |
      A BGP configuration, as described in FRR documentation.
    example: |-
      router bgp 1112
       bgp router-id 127.0.0.1
       bgp dampening 15 750 2000 61
  metadata:
    type: string
    description: |
      The metadata portion is the JSON configuration describing the mapping object.
    example:
      name: bgp_config_1
      description: |
        Configuration for BGP integration.
