type: object
description: |-
  GeoIP config summary read schema.
  
x-akamai:
  file-path: schemas/geoip-config.read-summary.yaml
additionalProperties: false
required:
- name
- type
- geoIpConfigId
properties:
  name:
    $ref: mapping.definitions.schema.yaml#/definitions/nameType
  type:
    $ref: geoip-config.definitions.schema.yaml#/definitions/typeType
  geoipConfigId:
    readOnly: true
    $ref: geoip-config.definitions.schema.yaml#/definitions/geoIpConfigIdType
