type: object
description: |-
  GeoIP config create schema.
  
x-akamai:
  file-path: schemas/geoip-config.create.yaml
additionalProperties: false
required:
- name
- type
properties:
  name:
    $ref: mapping.definitions.schema.yaml#/definitions/nameType
  type:
    $ref: geoip-config.definitions.schema.yaml#/definitions/typeType
  description:
    $ref: mapping.definitions.schema.yaml#/definitions/descriptionType
