type: object
description: |-
  GeoIP config collection.
  
x-akamai:
  file-path: schemas/geoip-config.collection.yaml
additionalProperties: false
required:
- geoIpConfigs
- page
properties:
  bgpConfigs:
    type: array
    description: |
      TBD. A page of GeoIpConfig objects matching the specified filtering and sorting criteria.
    items:
      $ref: geoip-config.read-summary.yaml
  page:
    $ref: definitions.yaml#/definitions/pageType
