type: object
description: |-
  GeoIP config update schema.
  
x-akamai:
  file-path: schemas/geoip-config.update.yaml
additionalProperties: false
required:
- name
- type
- geoIpConfigId
properties:
  name:
    $ref: mapping.definitions.schema.yaml#/definitions/nameType
  type:
    $ref: geoip-config.definitions.schema.yaml#/definitions/typeType
  description:
    $ref: mapping.definitions.schema.yaml#/definitions/descriptionType
  geoIpConfigId:
    readOnly: true
    $ref: geoip-config.definitions.schema.yaml#/definitions/geoIpConfigIdType
