description: |-
  GeoIP configuration object definitions.
  
x-akamai:
  file-path: schemas/geoip-config.definitions.schema.yaml
definitions:
  geoIpConfigIdType:
    type: integer
    description: |
      The unique identifier for a GeoIP configuration.
    minimum: 1
  typeType:
    type: string
    description: |
      Type of GeoIP data. Specifies the address type used in the GeoIP configuration file. `IPV4` indicates the GeoIP configuration file uses an IPv4 address. `IPV6` indicates the GeoIP configuration file uses an IPv6 address, `ZIP` indicates a MaxMind GeoIP2 zip file of both.
    enum:
    - IPV4
    - IPV6
    - ZIP
