type: object
x-akamai:
  file-path: schemas/geoip-config-multipart.yaml
additionalProperties: false
required:
- metadata
- config
properties:
  config:
    type: string
    description: |
      A GeoIP database as obtained from the vendor.
    example: |
      "1.0.0.0","1.0.0.253","16777216","16777471","AU","Australia"...
  metadata:
    type: string
    description: |
      The metadata portion is the JSON configuration describing the mapping object.
    example:
      name: geoip_config_1
      type: IPV4
      description: |
        Configuration for GeoIP integration.
