openapi: 3.0.0
info:
  title: delete
  version: v1
servers:
- url: http://{apiKey}-nsu.akamaihd.net
paths:
  /{cpCode}/{path}/{filename}:
    parameters:
    - $ref: parameters/X-Akamai-ACS-Action-delete.yaml
    - $ref: parameters/X-Akamai-ACS-Auth-Data.yaml
    - $ref: parameters/X-Akamai-ACS-Auth-Sign.yaml
    - $ref: parameters/Host.yaml
    - $ref: parameters/cpCode.yaml
    - $ref: parameters/path.yaml
    - $ref: parameters/filename.yaml
    put:
      operationId: put-delete
      summary: delete action
      tags:
      - API actions
      description: |
        Use this action to delete content from your storage group.
      responses:
        204:
          description: |
            The command succeeded, with no response data.
        400:
          $ref: errors/400.yaml
