openapi: 3.0.0
info:
  title: quick-delete
  version: v1
servers:
- url: http://{apiKey}-nsu.akamaihd.net
paths:
  /{cpCode}/{path}/{filename}:
    parameters:
    - $ref: parameters/X-Akamai-ACS-Action-quick-delete.yaml
    - $ref: parameters/X-Akamai-ACS-Auth-Data.yaml
    - $ref: parameters/X-Akamai-ACS-Auth-Sign.yaml
    - $ref: parameters/Host.yaml
    - $ref: parameters/cpCode.yaml
    - $ref: parameters/path.yaml
    - $ref: parameters/filename.yaml
    post:
      operationId: post-quick-delete
      summary: quick-delete action
      tags:
      - API actions
      description: |
        [TBD](https://techdocs.akamai.com/clone-akamai-test-project/reference/post-symlink) quick-delete.
      responses:
        204:
          description: |
            The command succeeded, with no response data.
        400:
          $ref: errors/400.yaml
