openapi: 3.0.0
info:
  title: Cloudlets
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-cloudlets-info.yaml
paths:
  /cloudlet-info:
    $ref: paths/cloudlets.yaml
  /cloudlet-info/{cloudletId}:
    $ref: paths/cloudlet.yaml
