openapi: 3.0.0
info:
  title: Cloudlets
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /cloudlet-info:
    $ref: paths/cloudlets.yaml
  /cloudlet-info/{cloudletId}:
    $ref: paths/cloudlet.yaml
