openapi: 3.0.0
info:
  title: Group-level Cloudlets
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /group-info:
    $ref: paths/groups.yaml
  /group-info/{groupId}:
    $ref: paths/group.yaml
