openapi: 3.0.0
info:
  title: Policies
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policies:
    $ref: paths/policies.yaml
  /policies/{policyId}:
    $ref: paths/policy.yaml
