info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Policies
  version: v2
openapi: 3.0.0
paths:
  /policies:
    $ref: paths/policies.yaml
  /policies/{policyId}:
    $ref: paths/policy.yaml
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-policies.yaml
