openapi: 3.0.0
info:
  title: Policy versions
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policies/{policyId}/versions:
    $ref: paths/policy-versions.yaml
  /policies/{policyId}/versions/{version}:
    $ref: paths/policy-version.yaml
  /policies/{policyId}/versions/{version}/rules:
    $ref: paths/rules.yaml
  /policies/{policyId}/versions/{version}/rules/{akaRuleId}:
    $ref: paths/rule.yaml
