info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Property associations
  version: v2
openapi: 3.0.0
paths:
  /policies/{policyId}/properties:
    $ref: paths/policy-properties.yaml
  /policies/{policyId}/properties/{propertyId}:
    $ref: paths/property.yaml
  /properties:
    $ref: paths/properties.yaml
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 05-property-info.yaml
