openapi: 3.0.0
info:
  title: Cloudlets origins for Application Load Balancer
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 06-origins.yaml
paths:
  /origins:
    $ref: paths/origins.yaml
  /origins/{originId}:
    $ref: paths/origin.yaml
  /origins/{originId}/versions:
    $ref: paths/origin-versions.yaml
  /origins/{originId}/versions/{version}:
    $ref: paths/origin-version.yaml
