openapi: 3.0.0
info:
  title: Load balancer activations
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /origins/currentActivations:
    $ref: paths/activations.yaml
  /origins/{originId}/activations:
    $ref: paths/origin-activations.yaml
