openapi: 3.0.0
info:
  title: Load balancer activations
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 07-origin-activations.yaml
paths:
  /origins/currentActivations:
    $ref: paths/activations.yaml
  /origins/{originId}/activations:
    $ref: paths/origin-activations.yaml
