openapi: 3.0.0
info:
  title: Policy activations
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 08-policy-activations.yaml
paths:
  /policies/{policyId}/activations:
    $ref: paths/policy-activations.yaml
  /policies/{policyId}/versions/{version}/activations:
    $ref: paths/policy-version-activations.yaml
