openapi: 3.0.0
info:
  title: Policy activations
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policies/{policyId}/activations:
    $ref: paths/policy-activations.yaml
  /policies/{policyId}/versions/{version}/activations:
    $ref: paths/policy-version-activations.yaml
