openapi: 3.0.0
info:
  title: Schemas
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /schemas:
    $ref: paths/schemas.yaml
  /schemas/{schemaName}:
    $ref: paths/schema.yaml
