info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Schemas
  version: v2
openapi: 3.0.0
paths:
  /schemas:
    $ref: paths/schemas.yaml
  /schemas/{schemaName}:
    $ref: paths/schema.yaml
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 09-schemas.yaml
