openapi: 3.0.0
info:
  title: Property Associations
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /properties:
    get:
      operationId: get-properties
      summary: List associated properties
      tags:
      - Associated properties
      description: |
        Run this operation to return the complete list of the associated properties.
      responses:
        200:
          description: |
            Returns information about the associated properties.
          content:
            application/json:
              example:
                $ref: examples/properties-get-200.json
              schema:
                $ref: schemas/get-properties-response.yaml
  /policies/{policyId}/properties:
    parameters:
    - $ref: parameters/policyId-path.yaml
    get:
      operationId: get-policy-properties
      summary: Get associated properties for a policy
      tags:
      - Associated properties
      description: |
        Run this operation to return the complete list of property associations for a specific policy with a given `policyId`.
      responses:
        200:
          description: |
            Returns information about the associated properties.
          content:
            application/json:
              example:
                $ref: examples/policyproperties-get-200.json
              schema:
                $ref: schemas/get-policy-properties-response.yaml
