name: configurationId
in: path
description: |-
  A unique identifier for a CAC configuration.
  
x-akamai:
  file-path: parameters/configuration-id-path.yaml
required: true
schema:
  type: integer
  example: 1234
