openapi: 3.0.0
info:
  title: Media Services Live 4
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-msl-http-ingest.yaml
paths:
  /media-services-live/http-ingest/data:
    $ref: paths/data-http-ingest.yaml
  /media-services-live/http-ingest/data-stores:
    $ref: paths/data-stores-http-ingest.yaml
  /media-services-live/http-ingest/data-stores/{dataStoreId}:
    $ref: paths/data-store-http-ingest.yaml
  /media-services-live/http-ingest/ep-switch/data:
    $ref: paths/data-ep-switch.yaml
  /media-services-live/http-ingest/origin-shield/data:
    $ref: paths/data-origin-shield.yaml
  /media-services-live/http-ingest/origin-shield/data-stores:
    $ref: paths/data-stores-origin-shield.yaml
