openapi: 3.0.0
info:
  title: Progressive Media Delivery
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-progressive-media-delivery.yaml
paths:
  /msod/pmd/data:
    $ref: paths/data-msod.yaml
  /msod/pmd/dimensions:
    $ref: paths/dimensions.yaml
  /msod/pmd/metrics:
    $ref: paths/metrics.yaml
