type: object
description: |-
  Returns social login application settings and setting values.
  
x-akamai:
  file-path: schemas/get_application_settings.yaml
additionalProperties: false
required:
- stat
- privacyPolicy
- favicon
- domainRedirect
- postToTokenUrl
- oneTimeUseTokens
- googleProfileUrl
properties:
  domainRedirect:
    type: string
    description: |
      URL redirect destination for users visiting your sign-in URL.
    minLength: 1
  favicon:
    type: string
    description: |
      Publicly accessible URL of your favicon. Favicons are icons that appear on web browser tabs, in a browser's address bar, and next to browser bookmarks. A `null` value means you haven't set a favicon.
    nullable: true
    minLength: 0
  googleProfileUrl:
    type: boolean
    description: |
      Deprecated.
  oneTimeUseTokens:
    type: boolean
    description: |
      If `true`, you can use a token just once before that token expires. If `false`, you can use the same token in more than one operation.
  postToTokenUrl:
    type: boolean
    description: |
      Deprecated.
  privacyPolicy:
    type: string
    description: |
      URL of your privacy policy. A `null` value means that you haven't set a privacy policy.
    nullable: true
    minLength: 0
  stat:
    type: string
    description: |
      Status of the operation. A value of `ok` means that the operation succeeded. A value of `error` means the operation couldn't complete because of problem with the request. A value of `fail` means the operation couldn't complete because of an error with the Identity Cloud backend infrastructure. Contact your Identity Cloud representative if you receive the `fail` error.
    enum:
    - ok
    - error
    - fail
