type: object
description: |-
  Modifies setting values for a social login application.
  
x-akamai:
  file-path: schemas/set-social-login-settings.yaml
additionalProperties: false
required:
- apiKey
properties:
  apiKey:
    type: string
    description: |
      Social login secret for authenticating the operation. To verify your API key, log in to Console and, on the **Manage Application** page, check the value of the **rpx_key**  setting. This value also appears on the **Settings** page in the Social Login dashboard. See [Get started](ref:get-started) for more information.
    minLength: 1
  domainRedirect:
    type: string
    description: |
      URL redirect destination for users visiting your sign-in URL. 
    minLength: 1
  favicon:
    type: string
    description: |
      Publicly accessible URL of your favicon. Favicons are icons that appear on web browser tabs, in a browser's address bar, and next to browser bookmarks. A `null` value means that you haven't set a favicon.
    nullable: true
    minLength: 0
  googleProfileUrl:
    type: boolean
    description: |
      Deprecated.
  oneTimeUseTokens:
    type: boolean
    description: |
      If `true`, you can use a token just once before that token expires. If `false`, you can use the same token in more than one operation.
  postToTokenUrl:
    type: boolean
    description: |
      Deprecated.
  privacyPolicy:
    type: string
    description: |
      URL of your privacy policy. A `null` value means that you haven't set a privacy policy.
    nullable: true
    minLength: 0
