type: object
description: |-
  Modifies social login application settings.
  
x-akamai:
  file-path: schemas/set_application_settings.yaml
additionalProperties: false
required:
- stat
properties:
  stat:
    type: string
    description: |
      Status of the operation. Possible values are: `ok`, `error`, or `fail`. A value of `ok` means that the operation was successful. A value of `error` means that the operation couldn't complete successfully because of problem with the request. A value of `fail` means that operation couldn't complete successfully because of an error with the Identity Cloud backend infrastructure. Contact your Identity Cloud representative if you receive the `fail` error.
    enum:
    - ok
    - error
    - fail
