openapi: 3.0.0
info:
  title: Properties
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-properties-api.yaml
paths:
  /user-admin/properties:
    $ref: paths/properties.yaml
  /user-admin/properties/{propertyId}:
    $ref: paths/property.yaml
  /user-admin/properties/{propertyId}/resources:
    $ref: paths/resources.yaml
  /user-admin/properties/{propertyId}/users:
    $ref: paths/users.yaml
  /user-admin/properties/{propertyId}/users/block:
    $ref: paths/block.yaml
