openapi: 3.0.0
info:
  title: Roles
  version: '3'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v3
tags:
- description: |
    Create and manage the roles for an account. Roles are lists of permissions
    that are explicitly tied to both a user and a group.
  name: Roles
- description: |
    Get information about roles you can include in a new custom role.
  name: Grantable roles
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-roles-api.yaml
paths:
  /user-admin/roles:
    $ref: paths/roles.yaml
  /user-admin/roles/grantable-roles:
    $ref: paths/grantable-roles.yaml
  /user-admin/roles/{roleId}:
    $ref: paths/role.yaml
