openapi: 3.0.0
info:
  title: Users, for administrators
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 04-user-api.yaml
paths:
  /user-admin/ui-identities:
    $ref: paths/ui-identities.yaml
  /user-admin/ui-identities/{uiIdentityId}:
    $ref: paths/ui-identity.yaml
  /user-admin/ui-identities/{uiIdentityId}/auth-grants:
    $ref: paths/auth-grants.yaml
  /user-admin/ui-identities/{uiIdentityId}/basic-info:
    $ref: paths/basic-info-user-admin.yaml
  /user-admin/ui-identities/{uiIdentityId}/groups/{groupId}/blocked-properties:
    $ref: paths/blocked-properties.yaml
  /user-admin/ui-identities/{uiIdentityId}/lock:
    $ref: paths/lock.yaml
  /user-admin/ui-identities/{uiIdentityId}/notifications:
    $ref: paths/notifications-user-admin.yaml
  /user-admin/ui-identities/{uiIdentityId}/reset-password:
    $ref: paths/reset-password.yaml
  /user-admin/ui-identities/{uiIdentityId}/set-password:
    $ref: paths/set-password.yaml
  /user-admin/ui-identities/{uiIdentityId}/tfa:
    $ref: paths/user-admin-tfa.yaml
  /user-admin/ui-identities/{uiIdentityId}/unlock:
    $ref: paths/unlock.yaml
