openapi: 3.0.0
info:
  title: API clients administration
  version: '3'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v3
tags:
- description: |
    Use helper calls to get information necessary to create an API client.
  name: Helper
- description: |
  Manage your own API clients.
  name: 'API client: self'
- description: |
    Manage API clients for the account.
  name: API clients
x-akamai:
  auth-type: EDGE_GRID
  file-path: 09-api-clients-admin.yaml
paths:
  /api-clients:
    $ref: paths/clients.yaml
  /api-clients/self:
    $ref: paths/self.yaml
  /api-clients/self/account-switch-keys:
    $ref: paths/account-switch-keys-self.yaml
  /api-clients/self/lock:
    $ref: paths/lock-clients.yaml
  /api-clients/{clientId}:
    $ref: paths/client.yaml
  /api-clients/{clientId}/account-switch-keys:
    $ref: paths/account-switch-keys-client.yaml
  /api-clients/{clientId}/lock:
    $ref: paths/lock-client.yaml
  /api-clients/{clientId}/unlock:
    $ref: paths/unlock-client.yaml
  /users:
    $ref: paths/users.yaml
  /users/{username}/allowed-apis:
    $ref: paths/allowed-apis.yaml
  /users/{username}/allowed-cpcodes:
    $ref: paths/allowed-cpcodes.yaml
  /users/{username}/group-access:
    $ref: paths/group-access.yaml
