name: bgpConfigId
in: path
description: |-
  Uniquely identifies a BGP configuration instance.
  
x-akamai:
  file-path: parameters/bgpConfigId-path.yaml
required: true
schema:
  type: integer
  example: 2072
