name: geoIpConfigId
in: path
description: |-
  Uniquely identifies a GeoIP configuration instance.
  
x-akamai:
  file-path: parameters/geoIpConfigId-path.yaml
required: true
schema:
  type: integer
  example: 2001
