type: object
description: |-
  Deploys your certificate to a network.
  
x-akamai:
  file-path: schemas/deployments.v8.yaml
additionalProperties: false
required:
- production
- staging
properties:
  production:
    type: object
    description: |
      Encapsulates information about your certificate's deployment on the production network.
    additionalProperties: false
    required:
    - multiStackedCertificates
    - networkConfiguration
    - primaryCertificate
    properties:
      multiStackedCertificates:
        type: array
        description: |
          Dual-stacked certificates include an ECDSA certificate in addition to an RSA certificate.
        minItems: 0
        items:
          type: object
          additionalProperties: false
          required:
          - certificate
          - trustChain
          properties:
            certificate:
              type: string
              description: |
                The certificate text.
              nullable: true
              minLength: 1
            expiry:
              type: string
              description: |
                The expiration date for the certificate.
              minLength: 1
            keyAlgorithm:
              type: string
              description: |
                The key algorithm for the multi-stacked certificate. This is either `ECDSA` or `RSA`.
              enum:
              - ECDSA
              - RSA
            signatureAlgorithm:
              type: string
              description: |
                Indicates the SHA (Secure Hash Algorithm) function. You can use either `SHA-1` for a 160-bit (20-byte) hash or `SHA-256` for a 256-bit (32-byte) hash.
              nullable: true
              enum:
              - SHA-1
              - SHA-256
            trustChain:
              type: string
              description: |
                The trust chain for the certificate.
              nullable: true
              minLength: 1
      networkConfiguration:
        type: object
        description: |
          Your certificate's deployment configuration settings on production.
        additionalProperties: false
        required:
        - quicEnabled
        - sniOnly
        properties:
          disallowedTlsVersions:
            type: array
            description: |
              Disallowed TLS protocols.
            minItems: 0
            items:
              type: string
              minLength: 1
          dnsNames:
            type: array
            description: |
              Names served by SNI-only enabled enrollments.
            minItems: 0
            items:
              type: string
              minLength: 1
          fipsMode:
            type: boolean
            description: |
              Enables Federal Information Processing Standards (FIPS) for the enrollment.          
          geography:
            type: string
            description: |
              Specifies the type of network where you want to deploy your certificate.  Use `core` to deploy across most of the world except for specially licensed areas.  Use `china+core` to include China, or `russia+core` to include Russia. Any non-`core` deployment needs to be enabled on your contract based on approval from the Chinese or Russian governments.
            enum:
            - core
            - china+core
            - russia+core
          mustHaveCiphers:
            type: string
            description: |
              Ciphers that you definitely want to include for your enrollment while deploying it on the network.
            minLength: 1
          ocspStapling:
            type: string
            description: |
              Indicates the OCSP stapling setting for the deployment. Use `on` to enable OCSP stapling, `off` to disable it, or `not-set` to ignore it.
            enum:
            - true
            - false
            - not-set
          preferredCiphers:
            type: string
            description: |
              Ciphers that you preferably want to include for your enrollment while deploying it on the network.
            minLength: 1
          quicEnabled:
            type: boolean
            description: |
              QUIC transport layer network protocol.
          secureNetwork:
            type: string
            description: |
              Identifies the type of deployment network. An `enhanced-tls` value means Akamai's more secure network with PCI compliance capability, while `standard-tls` means Akamai's standard secure network.
            enum:
            - enhanced-tls
            - standard-tls
          sniOnly:
            type: boolean
            description: |
              Server Name Indication (SNI) is an extension of the Transport Layer Security (TLS) networking protocol. It allows a server to present many certificates on the same IP address. All modern web browsers support the SNI extension. If you have the same SAN on two or more certificates with the SNI-only option set, Akamai may serve traffic using any certificate that matches the requested SNI hostname. You should avoid any certificates with overlapping SAN names when using SNI-only.
      ocspStapled:
        type: boolean
        description: |
          OCSP Stapling improves performance by including a valid OCSP response in every TLS handshake. We recommend all customers enable this feature.
      ocspUris:
        type: array
        description: |
          URI used for OCSP stapling validation.
        nullable: true
        minItems: 0
        items:
          type: string
          minLength: 1
      primaryCertificate:
        type: object
        description: |
          Primary certificate of the enrollment.
        additionalProperties: false
        required:
        - certificate
        - trustChain
        nullable: true
        properties:
          certificate:
            type: string
            description: |
              The certificate text.
            nullable: true
            minLength: 1
          expiry:
            type: string
            description: |
              The expiration date for the certificate.
            minLength: 1
          keyAlgorithm:
            type: string
            description: |
              The key algorithm for the multi-stacked certificate. This is either `ECDSA` or `RSA`.
            enum:
            - ECDSA
            - RSA
          signatureAlgorithm:
            type: string
            description: |
              Indicates the SHA (Secure Hash Algorithm) function. You can use either `SHA-1` for a 160-bit (20-byte) hash or `SHA-256` for a 256-bit (32-byte) hash.
            nullable: true
            enum:
            - SHA-1
            - SHA-256
          trustChain:
            type: string
            description: |
              The trust chain for the certificate.
            nullable: true
            minLength: 1
  staging:
    type: object
    description: |
      Encapsulates information about your certificate's deployment on the staging network.
    additionalProperties: false
    required:
    - multiStackedCertificates
    - networkConfiguration
    - primaryCertificate
    properties:
      multiStackedCertificates:
        type: array
        description: |
          Dual-stacked certificates today include an ECDSA certificate in addition to an RSA certificate.
        minItems: 0
        items:
          type: object
          additionalProperties: false
          required:
          - certificate
          - trustChain
          properties:
            certificate:
              type: string
              description: |
                The certificate text.
              nullable: true
              minLength: 1
            expiry:
              type: string
              description: |
                The expiration date for the certificate.
              minLength: 1
            keyAlgorithm:
              type: string
              description: |
                The key algorithm for the multi-stacked certificate. This is either `ECDSA` or `RSA`.
              enum:
              - ECDSA
              - RSA
            signatureAlgorithm:
              type: string
              description: |
                Indicates the SHA (Secure Hash Algorithm) function. You can use either `SHA-1` for a 160-bit (20-byte) hash or `SHA-256` for a 256-bit (32-byte) hash.
              nullable: true
              enum:
              - SHA-1
              - SHA-256
            trustChain:
              type: string
              description: |
                The trust chain for the certificate.
              nullable: true
              minLength: 1
      networkConfiguration:
        type: object
        description: |
          Encapsulates information about your certificate's deployment configuration settings on staging.
        additionalProperties: false
        required:
        - quicEnabled
        - sniOnly
        properties:
          disallowedTlsVersions:
            type: array
            description: |
              Disallowed TLS protocols.
            minItems: 0
            items:
              type: string
              minLength: 1
          dnsNames:
            type: array
            description: |
              Names served by SNI-only enabled enrollments.
            minItems: 0
            items:
              type: string
              minLength: 1
          fipsMode:
            type: boolean
            description: |
              Enables Federal Information Processing Standards (FIPS) for the enrollment.              
          geography:
            type: string
            description: |
              Specifies the type of network where you want to deploy your certificate.  Use `core` to deploy across most of the world except for specially licensed areas.  Use `china+core` to include China, or `russia+core` to include Russia. Any non-`core` deployment needs to be enabled on your contract based on approval from the Chinese or Russian governments.
            enum:
            - core
            - china+core
            - russia+core
          mustHaveCiphers:
            type: string
            description: |
              Ciphers that you definitely want to include for your enrollment while deploying it on the network.
            minLength: 1
          ocspStapling:
            type: string
            description: |
              Indicates the OCSP stapling setting for the deployment. Use `on` to enable OCSP stapling, `off` to disable it, or `not-set` to ignore it.
            enum:
            - true
            - false
            - not-set
          preferredCiphers:
            type: string
            description: |
              Ciphers that you preferably want to include for your enrollment while deploying it on the network.
            minLength: 1
          quicEnabled:
            type: boolean
            description: |
              QUIC transport layer network protocol.
          secureNetwork:
            type: string
            description: |
              The type of deployment network. A value of `standard-tls` means Akamai's standard secure network, while `enhanced-tls` means Akamai's more secure network with PCI compliance capability.
            enum:
            - enhanced-tls
            - standard-tls
          sniOnly:
            type: boolean
            description: |
              Server Name Indication (SNI) is an extension of the Transport Layer Security (TLS) networking protocol. It allows a server to present many certificates on the same IP address. All modern web browsers support the SNI extension. If you have the same SAN on two or more certificates with the SNI-only option set, Akamai may serve traffic using any certificate which matches the requested SNI hostname. You should avoid any certificates with overlapping SAN names when using SNI-only.
      ocspStapled:
        type: boolean
        description: |
          OCSP Stapling improves performance by including a valid OCSP response in every TLS handshake. You should enable this feature.
      ocspUris:
        type: array
        description: |
          URI used for OCSP stapling validation.
        nullable: true
        minItems: 0
        items:
          type: string
          minLength: 1
      primaryCertificate:
        type: object
        description: |
          The primary certificate of the enrollment.
        additionalProperties: false
        required:
        - certificate
        - trustChain
        nullable: true
        properties:
          certificate:
            type: string
            description: |
              The certificate text.
            nullable: true
            minLength: 1
          expiry:
            type: string
            description: |
              The expiration date for the certificate.
            minLength: 1
          keyAlgorithm:
            type: string
            description: |
              The key algorithm for the multi-stacked certificate. This is either `ECDSA` or `RSA`.
            enum:
            - ECDSA
            - RSA
          signatureAlgorithm:
            type: string
            description: |
              Identifies the SHA (Secure Hash Algorithm) function. The NSA (National Security Agency) designed this function to produce a hash of certificate contents, which is used in a digital signature. This is either `SHA-1` for a 160-bit (20-byte) hash or `SHA-256` for a 256-bit (32-byte) hash. To ensure a secure hash function, use `SHA-256`.
            nullable: true
            enum:
            - SHA-1
            - SHA-256
          trustChain:
            type: string
            description: |
              The trust chain for the certificate.
            nullable: true
            minLength: 1
