type: object
x-akamai:
  file-path: schemas/deployments.v3.yaml
additionalProperties: false
required:
- production
- staging
properties:
  production:
    type: object
    additionalProperties: false
    required:
    - certificate
    - networkConfiguration
    - trustChain
    properties:
      certificate:
        type: string
        nullable: true
      networkConfiguration:
        type: object
        additionalProperties: false
        properties:
          disallowedTlsVersions:
            type: array
            items:
              type: string
          geography:
            type: string
            description: |
              Specifies the type of network where you want to deploy your certificate.  Use `core` to deploy across most of the world except for specially licensed areas.  Use `china+core` to include China, or `russia+core` to include Russia. Any non-`core` deployment needs to be enabled on your contract based on approval from the Chinese or Russian governments.
            enum:
            - core
            - china+core
            - russia+core
          mustHaveCiphers:
            type: string
          preferredCiphers:
            type: string
          secureNetwork:
            type: string
          sni:
            type: object
            additionalProperties: false
            required:
            - cloneDnsNames
            nullable: true
            properties:
              cloneDnsNames:
                type: boolean
              dnsNames:
                type: array
                items:
                  type: string
      signatureAlgorithm:
        type: string
        nullable: true
      trustChain:
        type: string
        nullable: true
  staging:
    type: object
    additionalProperties: false
    required:
    - certificate
    - networkConfiguration
    - trustChain
    properties:
      certificate:
        type: string
        nullable: true
      networkConfiguration:
        type: object
        additionalProperties: false
        properties:
          disallowedTlsVersions:
            type: array
            items:
              type: string
          geography:
            type: string
            description: |
              Specifies the type of network where you want to deploy your certificate.  Use `core` to deploy across most of the world except for specially licensed areas.  Use `china+core` to include China, or `russia+core` to include Russia. Any non-`core` deployment needs to be enabled on your contract based on approval from the Chinese or Russian governments.
            enum:
            - core
            - china+core
            - russia+core
          mustHaveCiphers:
            type: string
          preferredCiphers:
            type: string
          secureNetwork:
            type: string
          sni:
            type: object
            additionalProperties: false
            required:
            - cloneDnsNames
            nullable: true
            properties:
              cloneDnsNames:
                type: boolean
              dnsNames:
                type: array
                items:
                  type: string
      signatureAlgorithm:
        type: string
        nullable: true
      trustChain:
        type: string
        nullable: true
