openapi: 3.0.0
info:
  title: Accounts
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/case-management/v3
tags:
- description: List accounts you can create a case for.
  name: Accounts
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-accounts.yaml
paths:
  /accounts-with-categories:
    $ref: paths/accounts-with-categories.yaml
