openapi: 3.0.0
info:
  title: Cases
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/case-management/v3
tags:
- description: Manage cases.
  name: Cases
- description: Manage case comments.
  name: Case comments
- description: Manage case attachments.
  name: Case attachments
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-cases.yaml
paths:
  /cases:
    $ref: paths/cases.yaml
  /cases/{caseId}:
    $ref: paths/case.yaml
  /cases/{caseId}/attachments:
    $ref: paths/attachments.yaml
  /cases/{caseId}/attachments/status/{uploadId}:
    $ref: paths/upload.yaml
  /cases/{caseId}/attachments/{attachmentId}:
    $ref: paths/attachment.yaml
  /cases/{caseId}/comments:
    $ref: paths/comments.yaml
  /cases/{caseId}/request-case-closure:
    $ref: paths/request-case-closure.yaml
