openapi: 3.0.0
info:
  title: Categories
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/case-management/v3
tags:
- description: List available case categories.
  name: Case categories
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-categories.yaml
paths:
  /categories/{categoryId}:
    $ref: paths/category.yaml
