openapi: 3.0.0
info:
  title: Permissions
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/eccu-api/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-permissions.yaml
paths:
  /permissions:
    $ref: paths/permissions.yaml
