openapi: 3.0.0
info:
  title: Properties
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/eccu-api/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-properties.yaml
paths:
  /properties:
    $ref: paths/properties.yaml
