openapi: 3.0.0
info:
  title: Requests
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/eccu-api/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-requests.yaml
paths:
  /requests:
    $ref: paths/requests.yaml
  /requests/{requestId}:
    $ref: paths/request.yaml
