openapi: 3.0.0
info:
  title: DataStream 2 configuration
  version: '1'
servers:
- url: https://{hostname}/datastream-config-api/v1/log
x-akamai:
  auth-type: EDGE_GRID
paths:
  /connectors:
    $ref: paths/connectors.yaml
  /datasets/template/{templateName}:
    $ref: paths/template.yaml
  /groups:
    $ref: paths/groups.yaml
  /products:
    $ref: paths/products.yaml
  /properties/group/{groupId}:
    $ref: paths/group.yaml
  /properties/product/{productId}/group/{groupId}:
    $ref: paths/group-product.yaml
  /streamTypes:
    $ref: paths/stream-types.yaml
  /streams:
    $ref: paths/streams.yaml
  /streams/{streamId}:
    $ref: paths/stream.yaml
  /streams/{streamId}/activate:
    $ref: paths/activate.yaml
  /streams/{streamId}/activationHistory:
    $ref: paths/activations.yaml
  /streams/{streamId}/deactivate:
    $ref: paths/deactivate.yaml
  /streams/{streamId}/history:
    $ref: paths/history.yaml
