type: object
description: |-
  Encapsulates direct connect settings associated with a stream. Akamai Direct Connect (ADC) lets you connect to the Akamai infrastructure without using a third-party IP transit provider. It provides private connectivity between the Akamai network and a router in your (on-premises) data center, or co-location environment.
  
x-akamai:
  file-path: schemas/direct-connect-settings-get-dto.yaml
additionalProperties: false
properties:
  enabled:
    type: boolean
    description: |
      Enables direct connect for the stream.
