type: object
description: |-
  Details about the stream provisioning status.
  
x-akamai:
  file-path: schemas/direct-connect-settings-dto.yaml
additionalProperties: false
properties:
  message:
    type: string
    description: |
      A message about the stream provisioning status.
  status:
    type: string
    description: |
      The status of the stream. Possible enum values are: `PENDING`, `PROVISIONED`, `FAILED`.
    enum:
    - PENDING
    - PROVISIONED
    - FAILED
  streamId:
    type: integer
    description: |
      A unique identifier for the stream.
