name: configId
in: path
description: |
  The unique identifier Akamai assigns to your Cloud Wrapper configuration.
required: true
schema:
  type: integer
  example: 12345
  format: int32
  minimum: 1
  maximum: 1000000000
