openapi: 3.0.0
info:
  title: Event types
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/event-viewer-api/v1
tags:
- description: Get data about user-defined events.
  name: Event types
x-akamai:
  auth-type: EDGE_GRID
  file-path: event-types.yaml
paths:
  /event-types:
    get:
      operationId: get-event-types
      summary: List event types
      tags:
      - Event types
      description: |
        Returns all defined event types with related event definitions.
      responses:
        200:
          description: |
            List Event Types.
          content:
            application/json:
              example:
                $ref: examples/event-types-200.json
              schema:
                $ref: schemas/event-types-200.yaml
