openapi: 3.0.0
info:
  title: Subscriptions
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/firewall-rules-manager/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-subscriptions.yaml
paths:
  /subscriptions:
    $ref: paths/subscriptions.yaml
