openapi: 3.0.0
info:
  title: OpenID Connect clients
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/{customerId}
x-akamai:
  auth-type: OAUTH
  file-path: oidc_clients.yaml
paths:
  /config/clients:
    post:
      operationId: post-oidc-clients
      summary: Create an OpenID Connect client
      tags:
      - OIDC clients
      description: |
        Creates an OpenID Connect client.
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/create-client-post.json
            schema:
              $ref: schemas/create-client-post.yaml
      responses:
        201:
          description: |
            OpenID Connect client creation successful.
          content:
            application/json:
              example:
                $ref: examples/create-client.json
              schema:
                $ref: schemas/create-client.yaml
        400:
          description: |
            [Bad request.](ref:400.yaml)
          content:
            application/json:
              example:
                $ref: examples/400.json
              schema:
                $ref: schemas/400.yaml
        401:
          description: |
            [Authentication required.](ref:401.yaml)
          content:
            application/json:
              example:
                $ref: examples/401.json
              schema:
                $ref: schemas/401.yaml
        403:
          description: |
            [Forbidden.](ref:403.yaml)
          content:
            application/json:
              example:
                $ref: examples/403.json
              schema:
                $ref: schemas/403.yaml
        404:
          description: |
            [Not found.](ref:400.yaml)
          content:
            application/json:
              example:
                $ref: examples/404.json
              schema:
                $ref: schemas/404.yaml
        409:
          description: |
            [Dependency error.](ref:409.yaml)
          content:
            application/json:
              example:
                $ref: examples/409.json
              schema:
                $ref: schemas/409.yaml
    get:
      operationId: get-oidc-clients
      summary: List OpenID Connect clients
      tags:
      - OIDC clients
      description: |
        Returns your OpenID Connect clients.
      responses:
        200:
          description: |
            OpenID Connect clients.
          content:
            application/json:
              example:
                $ref: examples/list-clients.json
              schema:
                $ref: schemas/list-clients.yaml
        401:
          description: |
            [Authentication required.](ref:401.yaml)
          content:
            application/json:
              example:
                $ref: examples/401.json
              schema:
                $ref: schemas/401.yaml
        403:
          description: |
            [Forbidden.](ref:403.yaml)
          content:
            application/json:
              example:
                $ref: examples/403.json
              schema:
                $ref: schemas/403.yaml
        404:
          description: |
            [Not found.](ref:404.yaml)
          content:
            application/json:
              example:
                $ref: examples/404.json
              schema:
                $ref: schemas/404.yaml
  /config/clients/{oidcClientId}:
    parameters:
    - $ref: parameters/oidcClientId-path.yaml
    get:
      operationId: get-oidc-client
      summary: Get an OpenID Connect client
      tags:
      - OIDC clients
      description: |
        Returns an OpenID Connect client.
      responses:
        200:
          description: |
            OpenID Connect client.
          content:
            application/json:
              example:
                $ref: examples/view-client.json
              schema:
                $ref: schemas/view-client.yaml
        400:
          description: |
            [Bad request.](ref:400.yaml)
          content:
            application/json:
              example:
                $ref: examples/400.json
              schema:
                $ref: schemas/400.yaml
        401:
          description: |
            [Authentication required.](ref:401.yaml)
          content:
            application/json:
              example:
                $ref: examples/401.json
              schema:
                $ref: schemas/401.yaml
        403:
          description: |
            [Forbidden.](ref:403.yaml)
          content:
            application/json:
              example:
                $ref: examples/403.json
              schema:
                $ref: schemas/403.yaml
        404:
          description: |
            [Not found.](ref:404.yaml)
          content:
            application/json:
              example:
                $ref: examples/404.json
              schema:
                $ref: schemas/404.yaml
        409:
          description: |
            [Dependency error.](ref:409.yaml)
          content:
            application/json:
              example:
                $ref: examples/409.json
              schema:
                $ref: schemas/409.yaml
    put:
      operationId: put-oidc-client
      summary: Modify an OpenID Connect client
      tags:
      - OIDC clients
      description: |
        Modifies an OpenID Connect client.
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/modify-client-put.json
            schema:
              $ref: schemas/modify-client-put.yaml
      responses:
        200:
          description: |
            OpenID Connect client modifications successful.
          content:
            application/json:
              example:
                $ref: examples/modify-client.json
              schema:
                $ref: schemas/modify-client.yaml
        400:
          description: |
            [Bad request.](ref:400.yaml)
          content:
            application/json:
              example:
                $ref: examples/400.json
              schema:
                $ref: schemas/400.yaml
        401:
          description: |
            [Authentication required.](ref:401.yaml)
          content:
            application/json:
              example:
                $ref: examples/401.json
              schema:
                $ref: schemas/401.yaml
        403:
          description: |
            [Forbidden.](ref:403.yaml)
          content:
            application/json:
              example:
                $ref: examples/403.json
              schema:
                $ref: schemas/403.yaml
        404:
          description: |
            [Not found.](ref:404.yaml)
          content:
            application/json:
              example:
                $ref: examples/404.json
              schema:
                $ref: schemas/404.yaml
        409:
          description: |
            [Dependency error.](ref:409.yaml)
          content:
            application/json:
              example:
                $ref: examples/409.json
              schema:
                $ref: schemas/409.yaml
    delete:
      operationId: delete-oidc-client
      summary: Delete an OpenID Connect client
      tags:
      - OIDC clients
      description: |
        Deletes an OpenID Connect client. Deleting an OIDC client doesn't delete the client's login policy or token policy. However, deleting an OIDC client does delete the OIDC client's application client.
      responses:
        204:
          description: |
            OpenID Connect client deletion successful.
        401:
          description: |
            [Authentication required.](ref:401.yaml)
          content:
            application/json:
              example:
                $ref: examples/401.json
              schema:
                $ref: schemas/401.yaml
        403:
          description: |
            [Forbidden.](ref:403.yaml)
          content:
            application/json:
              example:
                $ref: examples/403.json
              schema:
                $ref: schemas/403.yaml
        404:
          description: |
            [Not found.](ref:404.yaml)
          content:
            application/json:
              example:
                $ref: examples/404.json
              schema:
                $ref: schemas/404.yaml
  /config/clients/{oidcClientId}/secret:
    parameters:
    - $ref: parameters/oidcClientId-path.yaml
    post:
      operationId: post-reset-client-secret
      summary: Reset an OpenID Connect client secret
      tags:
      - OIDC client secrets
      description: |
        Resets the client secret for an OpenID Connect confidential client or configuration client. Use this operation to rotate client secrets.
      responses:
        200:
          description: |
            Client secret reset.
          content:
            application/json:
              example:
                $ref: examples/change-client-secret.json
              schema:
                $ref: schemas/change-client-secret.yaml
        400:
          description: |
            [Bad request.](ref:400.yaml)
          content:
            application/json:
              example:
                $ref: examples/400.json
              schema:
                $ref: schemas/400.yaml
        401:
          description: |
            [Authentication required.](ref:401.yaml)
          content:
            application/json:
              example:
                $ref: examples/401.json
              schema:
                $ref: schemas/401.yaml
        403:
          description: |
            [Forbidden.](ref:403.yaml)
          content:
            application/json:
              example:
                $ref: examples/403.json
              schema:
                $ref: schemas/403.yaml
    get:
      operationId: get-client-secret
      summary: Get an OpenID Connect client secret
      tags:
      - OIDC client secrets
      description: |
        Returns the client secret for an OIDC client. This is the only way to return the secret for a confidential or configuration client. Keep in mind that public clients don't have client secrets.
      responses:
        200:
          description: |
            Client secret.
          content:
            application/json:
              example:
                $ref: examples/view-client-secret.json
              schema:
                $ref: schemas/view-client-secret.yaml
        403:
          description: |
            [Forbidden.](ref:403.yaml)
          content:
            application/json:
              example:
                $ref: examples/403.json
              schema:
                $ref: schemas/403.yaml
        404:
          description: |
            [Not found.](ref:404.yaml)
          content:
            application/json:
              example:
                $ref: examples/404.json
              schema:
                $ref: schemas/404.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
- bearerAuth: []
