openapi: 3.0.0
info:
  title: Edge server locations
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: List the active edge servers available for running diagnostic tools.
  name: Edge server locations
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-edge-locations.yaml
paths:
  /edge-locations:
    $ref: paths/edge-locations.yaml
