openapi: 3.0.0
info:
  title: IP verification
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Check whether a specific IP address is part of the ​Akamai​ edge network.
  name: IP verification
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-verify-edge-ip.yaml
paths:
  /verify-edge-ip:
    $ref: paths/verify-edge-ip.yaml
