openapi: 3.0.0
info:
  title: IP network location
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Get geolocation data for an IP network.
  name: IP network location
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-locate-ip.yaml
paths:
  /locate-ip:
    $ref: paths/locate-ip.yaml
