openapi: 3.0.0
info:
  title: IP verification and location
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Check whether a specific IP address is part of the ​Akamai​ edge network.
    It also provides geolocation data for the IP's network.
  name: IP verification and location
x-akamai:
  auth-type: EDGE_GRID
  file-path: 04-verify-locate-ip.yaml
paths:
  /verify-locate-ip:
    $ref: paths/verify-locate-ip.yaml
