openapi: 3.0.0
info:
  title: GTM properties
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: List GTM properties that you can run diagnostics for. You need this
    data if you want to run [DIG](https://www.postman.com/akamai/workspace/akamai-apis/request/13085889-22cb1b16-0ca2-4cc4-9bbf-02ec762f8e77)
    or [MTR](https://www.postman.com/akamai/workspace/akamai-apis/request/13085889-744bc22d-3477-4462-9cdc-20dac9775447)
    operations for a GTM hostname.
  name: GTM properties
x-akamai:
  auth-type: EDGE_GRID
  file-path: 05-gtm-properties.yaml
paths:
  /gtm/gtm-properties:
    $ref: paths/gtm-properties.yaml
  /gtm/{property}/{domain}/gtm-property-ips:
    $ref: paths/gtm-property-ips.yaml
