openapi: 3.0.0
info:
  title: IPA hostnames
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: List IPA hostnames available for collecting diagnostic data.
  name: IPA hostnames
x-akamai:
  auth-type: EDGE_GRID
  file-path: 06-ipa-hostnames.yaml
paths:
  /ipa/hostnames:
    $ref: paths/hostnames.yaml
