openapi: 3.0.0
info:
  title: Error translator
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Use an error reference code to fetch the error summary and logs.
  name: Error translator
x-akamai:
  auth-type: EDGE_GRID
  file-path: 07-error-translator.yaml
paths:
  /error-translator:
    $ref: paths/error-translator.yaml
  /error-translator/requests/{requestId}:
    $ref: paths/error-translator-request.yaml
