openapi: 3.0.0
info:
  title: User diagnostic data
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run the User Diagnostic Data tool to collect and review diagnostic
    information for users facing issues with certain URLs or IP acceleration hostnames.
  name: User diagnostic data
x-akamai:
  auth-type: EDGE_GRID
  file-path: 08-user-diagnostic-data.yaml
paths:
  /user-diagnostic-data/groups:
    $ref: paths/groups.yaml
  /user-diagnostic-data/groups/{groupId}/records:
    $ref: paths/user-diagnostic-data.yaml
