openapi: 3.0.0
info:
  title: Metadata Tracer
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run metadata tracer to get information about latest behaviors and criteria
    applied to a [Property Manager property](https://techdocs.akamai.com/property-mgr/reference/api).
  name: Metadata Tracer
x-akamai:
  auth-type: EDGE_GRID
  file-path: 10-metadata-tracer.yaml
paths:
  /metadata-tracer:
    $ref: paths/metadata-tracer.yaml
  /metadata-tracer/locations:
    $ref: paths/locations.yaml
  /metadata-tracer/requests/{requestId}:
    $ref: paths/metadata-tracer-request.yaml
