openapi: 3.0.0
info:
  title: ESI debugger
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run the Edge Side Includes (ESI) Debugger to test and debug your web
    page.
  name: ESI debugger
x-akamai:
  auth-type: EDGE_GRID
  file-path: 11-debug-resource.yaml
paths:
  /esi-debugger-api/v1/debug:
    $ref: paths/esi-debugger.yaml
