openapi: 3.0.0
info:
  title: CURL
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run CURL to get the raw HTML for requests from any IP address or location.
    You can use it to verify if users can connect to a URL, check request and response
    headers, and test the URL with interjected headers.
  name: CURL
x-akamai:
  auth-type: EDGE_GRID
  file-path: 12-curl.yaml
paths:
  /curl:
    $ref: paths/curl.yaml
