openapi: 3.0.0
info:
  title: GREP
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run synchronous or asynchronous GREP operations to get logs for edge
    server IPs from either the last 6 or 24 hours depending on the server and traffic
    conditions.
  name: GREP
x-akamai:
  auth-type: EDGE_GRID
  file-path: 13-grep.yaml
paths:
  /grep:
    $ref: paths/grep.yaml
  /grep/requests/{requestId}:
    $ref: paths/grep-request.yaml
