openapi: 3.0.0
info:
  title: ARL translator
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Get details about an [Akamai Resource Locator](https://techdocs.akamai.com/edge-diagnostics/docs/arl-syntax)
    (ARL), which identifies URL content on each Akamai edge server.
  name: ARL translator
x-akamai:
  auth-type: EDGE_GRID
  file-path: 14-translated-url.yaml
paths:
  /translated-url:
    $ref: paths/translated-url.yaml
