openapi: 3.0.0
info:
  title: DIG
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run the DIG tool to get DNS details for a hostname of domain name from
    a particular location or edge server IP. The results may help you diagnose issues
    with domain name resolutions.
  name: DIG
x-akamai:
  auth-type: EDGE_GRID
  file-path: 15-dig.yaml
paths:
  /dig:
    $ref: paths/dig.yaml
