openapi: 3.0.0
info:
  title: MTR
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Use MTR to checks the traffic between a location or an IP belonging
    to an edge network and an IP or a hostname. With this, you can verify if the traffic
    between a specific source and destination suffers packets' loss or latency.
  name: MTR
x-akamai:
  auth-type: EDGE_GRID
  file-path: 16-mtr.yaml
paths:
  /mtr:
    $ref: paths/mtr.yaml
