openapi: 3.0.0
info:
  title: URL Health Check
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run the URL Health Check problem scenario to get full diagnostics of
    a URL. The scenario combines GREP, DIG, cURL, and MTR tools.
  name: URL Health Check
x-akamai:
  auth-type: EDGE_GRID
  file-path: 17-url-health-check.yaml
paths:
  /url-health-check:
    $ref: paths/url-health-check.yaml
  /url-health-check/requests/{requestId}:
    $ref: paths/url-health-check-request.yaml
