openapi: 3.0.0
info:
  title: Connectivity problems
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run the Connectivity problems scenario to troubleshoot slow download
    and high response time.
  name: Connectivity problems
x-akamai:
  auth-type: EDGE_GRID
  file-path: 18-connectivity-problems.yaml
paths:
  /connectivity-problems:
    $ref: paths/connectivity-problems.yaml
  /connectivity-problems/requests/{requestId}:
    $ref: paths/connectivity-problems-request.yaml
