openapi: 3.0.0
info:
  title: Content problems
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- description: Run the Content problems scenario to troubleshoot incorrect or missing
    objects or stale content being served and partial downloads.
  name: Content problems
x-akamai:
  auth-type: EDGE_GRID
  file-path: 19-content-problems.yaml
paths:
  /content-problems:
    $ref: paths/content-problems.yaml
  /content-problems/requests/{requestId}:
    $ref: paths/content-problems-request.yaml
