openapi: 3.0.0
info:
  title: Edge server locations
  version: v1
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- name: Edge server locations
  description: |
    List the active edge servers available for running diagnostic tools.
x-akamai:
  auth-type: EDGE_GRID
paths:
  /edge-locations:
    get:
      operationId: get-edge-locations
      summary: List available edge server locations
      tags:
      - Edge server locations
      description: |
        Lists active edge server locations you can use to run [Request content with cURL](ref:post-curl), [Get domain details with dig](ref:post-dig), [Test network connectivity with MTR](ref:post-mtr), [Run the URL health check](ref:post-url-health-check), [Run the connectivity problems scenario](ref:post-connectivity-problems), and [Run the content problems scenario](ref:post-content-problems) operations. To get a subset of edge servers supporting metadata tracer, run the [List available edge server locations for metadata tracing](ref:get-mdt-locations) operation.
      responses:
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        405:
          $ref: errors/405.yaml
        429:
          $ref: errors/429.yaml
        200:
          description: |
            The response lists available edge server locations.
          headers:
            X-RateLimit-Limit:
              $ref: headers/X-RateLimit-Limit.yaml
            X-RateLimit-Remaining:
              $ref: headers/X-RateLimit-Remaining.yaml
          content:
            application/json:
              example:
                $ref: examples/edgeLocations.json
              schema:
                $ref: schemas/edgeLocations.yaml
