openapi: 3.0.0
info:
  title: IP verification
  version: v1
servers:
- url: https://{hostname}/edge-diagnostics/v1
tags:
- name: IP verification
  description: |
    Check whether a specific IP address is part of the ​Akamai​ edge network.
x-akamai:
  auth-type: EDGE_GRID
paths:
  /verify-edge-ip:
    post:
      operationId: post-verify-edge-ip
      summary: Verify an IP
      tags:
      - IP verification
      description: |
        Verifies if an IP belongs to an edge server. For IPs verified positively, you can continue gathering diagnostic data with [Request content with cURL](ref:post-curl), [Get domain details with dig](ref:post-dig), or [Test network connectivity with MTR](ref:post-mtr) operations. You can enter up to 10 IPs.
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/verifyLocateIpsRequest.json
            schema:
              $ref: schemas/verifyLocateIpsRequest.yaml
      responses:
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        405:
          $ref: errors/405.yaml
        429:
          $ref: errors/429.yaml
        200:
          description: |
            The response provides the verification results and details about the request.
          headers:
            X-RateLimit-Limit:
              $ref: headers/X-RateLimit-Limit.yaml
            X-RateLimit-Remaining:
              $ref: headers/X-RateLimit-Remaining.yaml
          content:
            application/json:
              example:
                $ref: examples/verifyEdgeIp.json
              schema:
                $ref: schemas/verifyEdgeIp.yaml
