openapi: 3.0.0
info:
  title: Download notifications
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/ota/v1
tags:
- description: Get information about notifications for completed downloads to specific
    vehicles.
  name: Download notifications
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-download-notifications.yaml
paths:
  /download-notifications/{cpcode}:
    $ref: paths/download-notifications.yaml
