openapi: 3.0.0
info:
  title: Deletions
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/ccu/v3
tags:
- description: Purge by cache tag.
  name: Cache tag
- description: Purge by URL or by Akamai resource locator (ARL).
  name: URL/ARL
- description: Purge by content provider (CP) code.
  name: CP code
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-delete.yaml
paths:
  /delete/cpcode/{network}:
    $ref: paths/delete-cpcode.yaml
  /delete/tag/{network}:
    $ref: paths/delete-tag.yaml
  /delete/url/{network}:
    $ref: paths/delete-url.yaml
