openapi: 3.0.0
info:
  title: Invalidations
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/ccu/v3
x-akamai:
  auth-type: EDGE_GRID
  file-path: invalidate.yaml
paths:
  /invalidate/cpcode/{network}:
    $ref: paths/invalidate-cpcode.yaml
  /invalidate/tag/{network}:
    $ref: paths/invalidate-tag.yaml
  /invalidate/url/{network}:
    $ref: paths/invalidate-url.yaml
