openapi: 3.0.0
info:
  title: Rate limit status
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/ccu/v3
tags:
- description: |
    Groups operations that let you control rate limits.
  name: Rate limits
x-akamai:
  auth-type: EDGE_GRID
  file-path: rate-limit-status.yaml
paths:
  /rate-limit-status/{purge-type}:
    $ref: paths/rate-limit-status.yaml
