openapi: 3.0.0
info:
  title: Security Events
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/siem/v1
tags:
- description: |
    View security event data generated on the Akamai platform in your SIEM application.
  name: Events
x-akamai:
  auth-type: EDGE_GRID
  file-path: siem-resource.yaml
paths:
  /configs/{configId}:
    $ref: paths/config.yaml
