type: object
description: |
  Provides information about a product that you can enable log collection for and the groups that have permission to access this product. It also specifies a list of data set templates available for this product.
additionalProperties: false
properties:
  productId:
    type: string
    description: |
      Identifies the product.
  productName:
    type: string
    description: |
      The name of the product.
  groups:
    type: array
    items:
      description: |
        A list of groups that has access to the product.
      $ref: group.yaml
  templates:
    type: array
    items:
      description: |
        A list of data set templates that you can use with this product in a stream.
      $ref: template.yaml
