openapi: 3.0.0
info:
  title: AUP event reports
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports about Acceptable User Policy (AUP) events or get information about existing AUP events.
  name: AUP events
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-aup-event-details.yaml
paths:
  /configs/{configId}/aup-events/aggregate:
    $ref: paths/aup-events-aggregate.yaml
  /configs/{configId}/aup-events/details:
    $ref: paths/aup-events-details.yaml
  /configs/{configId}/aup-events/time-series:
    $ref: paths/aup-events-time-series.yaml
