openapi: 3.0.0
info:
  title: DNS activity reports
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports on threats detected when accessing a malicious domain.
  name: DNS activity reports
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-dns-activity-report.yaml
paths:
  /configs/{configId}/dns-activities/aggregate:
    $ref: paths/dns-activities-aggregate.yaml
  /configs/{configId}/dns-activities/details:
    $ref: paths/dns-activities-details.yaml
  /configs/{configId}/dns-activities/time-series:
    $ref: paths/dns-activities-time-series.yaml
