openapi: 3.0.0
info:
  title: Network traffic connections reports
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports on all network traffic directed to SIA, including suspicious traffic or traffic that bypasses the SIA Proxy.
  name: Network traffic connections
x-akamai:
  auth-type: EDGE_GRID
  file-path: 05-network-traffic-connections.yaml
paths:
  /configs/{configId}/network-traffic/connections/aggregate:
    $ref: paths/network-traffic-aggregate.yaml
  /configs/{configId}/network-traffic/connections/details:
    $ref: paths/network-traffic-details.yaml
  /configs/{configId}/network-traffic/connections/time-series:
    $ref: paths/network-traffic-time-series.yaml
