openapi: 3.0.0
info:
  title: IDP systems reports
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Get information about identity provider (IdP) access logs.
  name: IDP access logs
x-akamai:
  auth-type: EDGE_GRID
  file-path: 07-idp-access-logs.yaml
paths:
  /configs/{configId}/access-logs/details:
    $ref: paths/access-logs-details.yaml
