openapi: 3.0.0
info:
  title: Indicators of Compromise (IOC) reports
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports for Indicators of Compromise (IOC) records. IOCs are artifacts observed on a network or in an operating system that indicate a computer intrusion with high confidence.
  name: IOC reports
- description: |
    Generate reports on the types of Indicators of Compromise (IOC) configured for your SIA implementation. IOCs are artifacts observed on a network or in an operating system that indicate a computer intrusion with high confidence.
  name: IOC detail reports
x-akamai:
  auth-type: EDGE_GRID
  file-path: 08-ioc.yaml
paths:
  /configs/{configId}/ioc/time-series:
    $ref: paths/ioc-time-series.yaml
  /ioc/changes:
    $ref: paths/changes.yaml
  /ioc/details:
    $ref: paths/ioc-details.yaml
  /ioc/details/aup:
    $ref: paths/aup.yaml
  /ioc/details/avc:
    $ref: paths/avc.yaml
  /ioc/details/cidr:
    $ref: paths/cidr.yaml
  /ioc/domain-tree:
    $ref: paths/domain-tree.yaml
