openapi: 3.0.0
info:
  title: DeepScan event reports
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports of deepscan data for a configuration's offline network.
  name: Deepscan reports
x-akamai:
  auth-type: EDGE_GRID
  file-path: 09-deepscan-report.yaml
paths:
  /configs/{configId}/deep-scan-reports:
    $ref: paths/deep-scan-reports.yaml
