openapi: 3.0.0
info:
  title: Threat metadata report
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Get reports on metadata threats.
  name: Threats
x-akamai:
  auth-type: EDGE_GRID
  file-path: 10-threats.yaml
paths:
  /configs/{configId}/threats/threat-meta:
    $ref: paths/threat-meta.yaml
