openapi: 3.0.0
info:
  title: Feedback reports
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate domain-level threat reports or get feedback about a domain.
  name: Feedback reports
x-akamai:
  auth-type: EDGE_GRID
  file-path: 11-feedbacks-report.yaml
paths:
  /configs/{configId}/feedbacks/details:
    $ref: paths/feedbacks-details.yaml
