openapi: 3.0.0
info:
  title: Threat metadata report
  version: v3
servers:
- url: https://{hostname}/etp-report/v3
tags:
- name: Threats
  description: |
    Get reports on metadata threats.
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/threats/threat-meta:
    parameters:
    - $ref: parameters/configId-path.yaml
    get:
      operationId: get-threat-metadata
      summary: Get threat metadata report
      tags:
      - Threats
      description: |
        Returns the threat metadata.
      responses:
        200:
          description: |
            Successful response containing threat metadata.
          content:
            application/json:
              example:
                $ref: examples/threat-meta-response-200.json
              schema:
                $ref: schemas/threat-meta-response.yaml
        400:
          $ref: errors/400.yaml
        403:
          $ref: errors/InsufficientPermissions-403.yaml
        404:
          $ref: errors/notFound-404.yaml
