openapi: 3.0.0
info:
  title: Contracts
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/contract-api/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-contracts.yaml
paths:
  /contracts/identifiers:
    $ref: paths/contract-ids.yaml
  /contracts/{contractId}/products/summaries:
    $ref: paths/contract-summaries.yaml
