openapi: 3.0.0
info:
  title: Reporting groups
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/contract-api/v1
tags:
- description: Get information about your reporting groups, which are CP codes grouped
    for billing purposes.
  name: Reporting groups
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-reporting-groups.yaml
paths:
  /reportingGroups:
    $ref: paths/reporting-groups.yaml
  /reportingGroups/identifiers:
    $ref: paths/reporting-group-ids.yaml
  /reportingGroups/{reportingGroupId}/products/summaries:
    $ref: paths/reporting-group-summaries.yaml
