openapi: 3.0.0
info:
  title: Mapped IP addresses
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/ip-protect/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-mips.yaml
paths:
  /mips:
    $ref: paths/mips.yaml
