openapi: 3.0.0
info:
  title: Policy domains
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/ip-protect/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-policy-domains.yaml
paths:
  /policy-domains:
    $ref: paths/policy-domains.yaml
  /policy-domains/vips:
    $ref: paths/vips.yaml
  /policy-domains/vips/health-stats:
    $ref: paths/health-stats-vips.yaml
  /policy-domains/{pdName}:
    $ref: paths/policy-domain.yaml
  /policy-domains/{pdName}/configs:
    $ref: paths/configs.yaml
  /policy-domains/{pdName}/pd-subnets/allocate:
    $ref: paths/allocate.yaml
  /policy-domains/{pdName}/vips/health-stats:
    $ref: paths/health-stats-policy-domain.yaml
