openapi: 3.0.0
info:
  title: Cloudlets
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/v3
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-cloudlet-info.yaml
paths:
  /cloudlet-info:
    $ref: paths/cloudlet.yaml
