openapi: 3.0.0
info:
  title: Group-level Cloudlets
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-group-info.yaml
paths:
  /group-info:
    $ref: paths/groups.yaml
  /group-info/{groupId}:
    $ref: paths/group.yaml
