openapi: 3.0.0
info:
  title: Policies
  version: v3
servers:
- url: https://{hostname}/cloudlets/v3
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policies:
    $ref: paths/policies.yaml
  /policies/{policyId}:
    $ref: paths/policy.yaml
  /policies/{policyId}/clone:
    $ref: paths/clone.yaml
