openapi: 3.0.0
info:
  title: Policy versions
  version: v3
servers:
- url: https://{hostname}/cloudlets/v3
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policies/{policyId}/versions:
    $ref: paths/versions.yaml
  /policies/{policyId}/versions/{version}:
    $ref: paths/version.yaml
