openapi: 3.0.0
info:
  title: Activations
  version: v3
servers:
- url: https://{hostname}/cloudlets/v3
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policies/{policyId}/activations:
    $ref: paths/activations.yaml
  /policies/{policyId}/activations/{activationId}:
    $ref: paths/activation.yaml
