openapi: 3.0.0
info:
  title: Active properties
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/v3
x-akamai:
  auth-type: EDGE_GRID
  file-path: 05-policy-propertyinfo.yaml
paths:
  /policies/{policyId}/properties:
    $ref: paths/properties.yaml
