openapi: 3.0.0
info:
  title: Property associations
  version: v2
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policies/{policyId}/properties:
    $ref: paths/policy-properties.yaml
  /policies/{policyId}/properties/{propertyId}:
    $ref: paths/property.yaml
  /properties:
    $ref: paths/properties.yaml
