openapi: 3.0.0
info:
  title: Property Associations
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cloudlets/api/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: property-info.yaml
paths:
  /policies/{policyId}/properties:
    parameters:
    - $ref: parameters/policyId-path.yaml
    get:
      operationId: get-policy-properties
      summary: Get associated properties for a policy
      tags:
      - Associated properties
      description: |
        Run this operation to return the complete list of property associations for a specific policy with a given `policyId`.
      responses:
        200:
          description: |
            Returns information about the associated properties.
          content:
            application/json:
              example:
                $ref: examples/policyproperties-get-200.json
              schema:
                $ref: schemas/get-policy-properties-response.yaml
  /policies/{policyId}/properties/{propertyId}:
    parameters:
    - $ref: parameters/policyId-path.yaml
    - $ref: parameters/propertyId-path.yaml
    - $ref: parameters/network-query.yaml
    delete:
      operationId: delete-policy-properties
      summary: Remove a property from a policy
      tags:
      - Associated properties
      description: |
        Run this operation to remove the link between the specified `policyId` and `propertyId`. If the `staging` or `prod` is not specified in the network query parameter, then the link is removed in both the networks if present. It does not delete the property or the policy.
      responses:
        204:
          description: |
            The property is no longer associated with the policy.
  /properties:
    get:
      operationId: get-properties
      summary: List associated properties
      tags:
      - Associated properties
      description: |
        Run this operation to return the complete list of the associated properties.
      responses:
        200:
          description: |
            Returns information about the associated properties.
          content:
            application/json:
              example:
                $ref: examples/properties-get-200.json
              schema:
                $ref: schemas/get-properties-response.yaml
