openapi: 3.0.0
info:
  title: Directories
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-directories.yaml
paths:
  /mgmt-pop/directories:
    $ref: paths/directories.yaml
  /mgmt-pop/directories/createusers/status/{cmd_id}:
    $ref: paths/cmd-create-users.yaml
  /mgmt-pop/directories/reinviteusers/status/{cmd_id}:
    $ref: paths/cmd-reinvite-users.yaml
  /mgmt-pop/directories/search:
    $ref: paths/search.yaml
  /mgmt-pop/directories/verify:
    $ref: paths/verify.yaml
  /mgmt-pop/directories/verify/{cmd_id}:
    $ref: paths/cmd-verify.yaml
  /mgmt-pop/directories/{directory_id}:
    $ref: paths/directory.yaml
  /mgmt-pop/directories/{directory_id}/apps:
    $ref: paths/apps-per-directory.yaml
  /mgmt-pop/directories/{directory_id}/createusers:
    $ref: paths/create-users.yaml
  /mgmt-pop/directories/{directory_id}/deleteusers:
    $ref: paths/delete-users.yaml
  /mgmt-pop/directories/{directory_id}/groups:
    $ref: paths/groups-per-dir.yaml
  /mgmt-pop/directories/{directory_id}/groups/{group_id}:
    $ref: paths/group.yaml
  /mgmt-pop/directories/{directory_id}/groups/{group_id}/users:
    $ref: paths/users-per-group.yaml
  /mgmt-pop/directories/{directory_id}/reinviteusers:
    $ref: paths/reinvite-users.yaml
  /mgmt-pop/directories/{directory_id}/sync:
    $ref: paths/sync.yaml
  /mgmt-pop/directories/{directory_id}/users:
    $ref: paths/users.yaml
  /mgmt-pop/directories/{directory_id}/users/autocomplete:
    $ref: paths/auto-complete.yaml
  /mgmt-pop/directories/{directory_id}/users/byname/{user_id}:
    $ref: paths/user.yaml
  /mgmt-pop/groupmembership:
    $ref: paths/group-memberships.yaml
  /mgmt-pop/groupmembership/{groupmembership_id}:
    $ref: paths/group-membership.yaml
  /mgmt-pop/tenant/mfa/reset:
    $ref: paths/reset.yaml
