openapi: 3.0.0
info:
  title: Connectors
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 04-agents.yaml
paths:
  /mgmt-pop/agents:
    $ref: paths/agents.yaml
  /mgmt-pop/agents/{uuid_url}:
    $ref: paths/uuid-url.yaml
  /mgmt-pop/agents/{uuid_url}/approve:
    $ref: paths/approve.yaml
  /mgmt-pop/agents/{uuid_url}/system-metrics:
    $ref: paths/system-metrics.yaml
  /mgmt-pop/agents/{uuid_url}/upgrade-os-pkgs:
    $ref: paths/upgrade-os-pkgs.yaml
