openapi: 3.0.0
info:
  title: Certificates
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 05-certificates.yaml
paths:
  /mgmt-pop/certificates:
    $ref: paths/certificates.yaml
  /mgmt-pop/certificates/ca_attributes:
    $ref: paths/ca-attributes.yaml
  /mgmt-pop/certificates/{certificateId}:
    $ref: paths/certificate.yaml
  /mgmt-pop/certificates/{certificateId}/upload:
    $ref: paths/upload.yaml
