openapi: 3.0.0
info:
  title: Rules
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 06-services.yaml
paths:
  /mgmt-pop/services:
    $ref: paths/services.yaml
  /mgmt-pop/services/{id}:
    $ref: paths/id.yaml
  /mgmt-pop/services/{id}/rules:
    $ref: paths/rules-per-service.yaml
