openapi: 3.0.0
info:
  title: Device posture
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 07-device-posture.yaml
paths:
  /device-posture/inventory/device-history/{deviceId}:
    $ref: paths/device.yaml
  /device-posture/inventory/device/{deviceId}/op/clear:
    $ref: paths/clear.yaml
  /device-posture/inventory/list:
    $ref: paths/list.yaml
  /device-posture/inventory/summary/anti-malware-status:
    $ref: paths/anti-malware-status.yaml
  /device-posture/inventory/summary/browsers:
    $ref: paths/browsers.yaml
  /device-posture/inventory/summary/device-biometric:
    $ref: paths/device-biometric.yaml
  /device-posture/inventory/summary/device-jailbroken:
    $ref: paths/device-jailbroken.yaml
  /device-posture/inventory/summary/device-roll-ups:
    $ref: paths/device-roll-ups.yaml
  /device-posture/inventory/summary/device-screen-lock:
    $ref: paths/device-screen-lock.yaml
  /device-posture/inventory/summary/firewall-status:
    $ref: paths/firewall-status.yaml
  /device-posture/inventory/summary/os:
    $ref: paths/os.yaml
  /device-posture/inventory/summary/risk-assessment:
    $ref: paths/risk-assessment.yaml
  /device-posture/inventory/summary/system-disk-encryption:
    $ref: paths/system-disk-encryption.yaml
  /device-posture/risk-assessment/available-browsers:
    $ref: paths/available-browsers.yaml
  /device-posture/risk-assessment/available-client-ver:
    $ref: paths/available-client-ver.yaml
  /device-posture/risk-assessment/available-os-ver:
    $ref: paths/available-os-ver.yaml
  /device-posture/risk-assessment/ca-ocsp:
    $ref: paths/ca-ocsp.yaml
  /device-posture/risk-assessment/certificate-profiles:
    $ref: paths/certificate-profiles.yaml
  /device-posture/risk-assessment/certificate-profiles/{certificateProfileId}:
    $ref: paths/certificate-profile.yaml
  /device-posture/risk-assessment/certificate-usage/anti-malware-profiles:
    $ref: paths/anti-malware-profiles.yaml
  /device-posture/risk-assessment/certificate-usage/anti-malware-profiles/{antiMalwareProfileId}:
    $ref: paths/anti-malware-profile.yaml
  /device-posture/risk-assessment/certificate-usage/ca:
    $ref: paths/ca.yaml
  /device-posture/risk-assessment/certificate-usage/ocsp:
    $ref: paths/ocsp.yaml
  /device-posture/risk-assessment/chosen-versions:
    $ref: paths/chosen-versions.yaml
  /device-posture/risk-assessment/chosen-versions/test:
    $ref: paths/test-chosen-versions.yaml
  /device-posture/risk-assessment/os-names:
    $ref: paths/os-names.yaml
  /device-posture/risk-assessment/partner/carbon-black:
    $ref: paths/carbon-black.yaml
  /device-posture/risk-assessment/partner/carbon-black/status:
    $ref: paths/status-carbon-black.yaml
  /device-posture/risk-assessment/partner/carbon-black/test:
    $ref: paths/test-carbon-black.yaml
  /device-posture/risk-assessment/partner/carbon-black/test/{integration_id}:
    $ref: paths/integration-carbon-black-test.yaml
  /device-posture/risk-assessment/partner/carbon-black/{integration_id}:
    $ref: paths/integration-carbon-black.yaml
  /device-posture/risk-assessment/partner/crowdstrike:
    $ref: paths/crowdstrike.yaml
  /device-posture/risk-assessment/partner/crowdstrike/status:
    $ref: paths/status-crowdstrike.yaml
  /device-posture/risk-assessment/partner/crowdstrike/test:
    $ref: paths/test-crowdstrike.yaml
  /device-posture/risk-assessment/partner/crowdstrike/test/{integration_id}:
    $ref: paths/integration-crowdstrike-test.yaml
  /device-posture/risk-assessment/partner/crowdstrike/{integration_id}:
    $ref: paths/integration-crowdstrike.yaml
  /device-posture/risk-assessment/signal-names:
    $ref: paths/signal-names.yaml
  /device-posture/risk-assessment/tags:
    $ref: paths/tags.yaml
  /device-posture/risk-assessment/tags/{ruleId}:
    $ref: paths/rule-tags.yaml
  /device-posture/risk-assessment/test/{ruleId}:
    $ref: paths/rule-test.yaml
  /device-posture/risk-assessment/tiers:
    $ref: paths/tiers.yaml
  /device-posture/risk-assessment/tiers/{ruleId}:
    $ref: paths/rule-tiers.yaml
  /device-posture/risk-assessment/versions/client_version:
    $ref: paths/client-version.yaml
