openapi: 3.0.0
info:
  title: Admin events reports
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 08-admin-events-reports.yaml
paths:
  /mgmt-pop/adminevents-reports/ops/reports:
    $ref: paths/reports.yaml
