openapi: 3.0.0
info:
  title: Certificates
  version: '1'
servers:
- url: https://{hostname}/crux/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /mgmt-pop/certificates:
    post:
      operationId: post-certificate
      summary: Create a certificate
      tags:
      - Certificates
      description: |
        Creates a new certificate.
      parameters:
      - $ref: parameters/contractId-query.yaml
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/certificate-post-body-manually.json
            schema:
              $ref: schemas/certificate_post.yaml
      responses:
        200:
          description: |
            Successful response.
          content:
            application/json:
              example:
                $ref: examples/certificate-post-body-200-manually.json
              schema:
                $ref: schemas/certificate_post.yaml
    get:
      operationId: get-certificates
      summary: List certificates
      tags:
      - Certificates
      description: |
        Lists certificates.
      parameters:
      - $ref: parameters/contractId-query.yaml
      - $ref: parameters/pageable_limit.yaml
      - $ref: parameters/pageable_offset.yaml
      responses:
        200:
          description: |
            Successful response.
          content:
            application/json:
              example:
                $ref: examples/certificate-get-list-200.json
              schema:
                $ref: schemas/certificate_list.yaml
  /mgmt-pop/certificates/{certificateId}:
    parameters:
    - $ref: parameters/certificateId-path.yaml
    get:
      operationId: get-certificate
      summary: Get a certificate
      tags:
      - Certificates
      description: |
        Retrieves a single certificate by ID.
      parameters:
      - $ref: parameters/contractId-query.yaml
      responses:
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        404:
          $ref: errors/404.yaml
        405:
          $ref: errors/405.yaml
        415:
          $ref: errors/415.yaml
        200:
          description: |
            Successful response.
          content:
            application/json:
              example:
                $ref: examples/certificate-post-body-200-file.json
              schema:
                $ref: schemas/certificate_post.yaml
    put:
      operationId: put-certificate
      summary: Modify a manual certificate
      tags:
      - Certificates
      description: |
        Updates an existing manual certificate.
      parameters:
      - $ref: parameters/contractId-query.yaml
      requestBody:
        required: true
        content:
          application/json:
            example:
              $ref: examples/certificate-put-body.json
            schema:
              $ref: schemas/certificate_put.yaml
      responses:
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        404:
          $ref: errors/404.yaml
        405:
          $ref: errors/405.yaml
        415:
          $ref: errors/415.yaml
        200:
          description: |
            Successful response.
          content:
            application/json:
              example:
                $ref: examples/certificate-put-200.json
              schema:
                $ref: schemas/certificate_post.yaml
    delete:
      operationId: delete-certificate
      summary: Delete a certificate
      tags:
      - Certificates
      description: |
        Removes an existing certificate.
      parameters:
      - $ref: parameters/contractId-query.yaml
      responses:
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        404:
          $ref: errors/404.yaml
        405:
          $ref: errors/405.yaml
        415:
          $ref: errors/415.yaml
        204:
          description: |
            Successful response.
  /mgmt-pop/certificates/{certificateId}/upload:
    parameters:
    - $ref: parameters/certificateId-path.yaml
    post:
      operationId: post-certificate-upload
      summary: Upload a certificate
      tags:
      - Certificates
      description: |
        Modifies a certificate.
      parameters:
      - $ref: parameters/contractId-query.yaml
      requestBody:
        required: true
        content:
          multipart/form-data:
            example:
              $ref: examples/certificate-post-body-manually.json
            schema:
              $ref: schemas/certificate_post_upload.yaml
      responses:
        200:
          description: |
            Successful response.
          content:
            application/json:
              example:
                $ref: examples/certificate-post-body-200-upload.json
              schema:
                $ref: schemas/certificate_post.yaml
  /mgmt-pop/certificates/ca_attributes:
    get:
      operationId: get-certificates-ca-attributes
      summary: List CA certificate attributes
      tags:
      - Certificates
      description: |
        Lists CA attributes.
      parameters:
      - $ref: parameters/contractId-query.yaml
      responses:
        200:
          description: |
            Successful response.
          content:
            application/json:
              example:
                $ref: examples/certificates-ca-attributes-200.json
              schema:
                $ref: schemas/ca-certificate.yaml
