openapi: 3.0.0
info:
  title: Adaptive Acceleration Report
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/adaptive-acceleration/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: adaptive-acceleration-report.yaml
paths:
  /properties/{propertyId}:
    $ref: paths/property.yaml
  /properties/{propertyId}/reset:
    $ref: paths/reset.yaml
