openapi: 3.0.0
info:
  title: Prolexic Analytics
  version: '2'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/prolexic-analytics/v2
- url: http://prolexic-analytics/v2
tags:
- description: |
  View attack event reports.
  name: Attack reports
- description: |
    View Routed 3.0 tunnel BGP session data.
  name: Routed BGP sessions
- description: |
  View critical event reports.
  name: Critical events
- description: |
  View event reports.
  name: Events
- description: |
  View network traffic metrics.
  name: Metrics
- description: |
    View network traffic metric types.
  name: Metric types
- description: |
    View account and contract details for customer names.
  name: Customer names
- description: |
    View Routed 3.0 GRE and Routed 3.0 GRE over ADC tunnel routes data.
  name: Routed tunnel routes
- description: |
    View time series event data reports.
  name: Time series data
x-akamai:
  auth-type: EDGE_GRID
  file-path: prolexic-analytics.yaml
paths:
  /attack-reports/contract/{contract}/attack-id/{attackId}:
    $ref: paths/attack.yaml
  /attack-reports/contract/{contract}/start/{start}/end/{end}:
    $ref: paths/attack-reports.yaml
  /critical-events/contract/{contract}:
    $ref: paths/critical-event-contract.yaml
  /customer/names:
    $ref: paths/names.yaml
  /events/contract/{contract}:
    $ref: paths/event-contract.yaml
  /metric-types/{contract}:
    $ref: paths/metric-contract.yaml
  /metrics:
    $ref: paths/metrics.yaml
  /routed/tunnel/bgp-sessions:
    $ref: paths/bgp-sessions.yaml
  /routed/tunnel/health:
    $ref: paths/health.yaml
  /routed/tunnel/routes:
    $ref: paths/routes.yaml
  /time-series-data:
    $ref: paths/time-series-data.yaml
