openapi: 3.0.0
info:
  title: Groups
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-groups-api.yaml
paths:
  /user-admin/groups:
    $ref: paths/groups.yaml
  /user-admin/groups/move:
    $ref: paths/move.yaml
  /user-admin/groups/move/{sourceGroupId}/{destinationGroupId}/affected-users:
    $ref: paths/affected-users.yaml
  /user-admin/groups/{groupId}:
    $ref: paths/group.yaml
