openapi: 3.0.0
info:
  title: Groups
  version: '3'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v3
tags:
- description: |
    Manage groups for your account. Groups are organizational containers
    for the objects you use in Control Center.
  name: Groups
- description: |
    Move nested groups within the same parent hierarchy.
  name: Move groups
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-groups-api.yaml
paths:
  /user-admin/groups:
    $ref: paths/groups.yaml
  /user-admin/groups/move:
    $ref: paths/move.yaml
  /user-admin/groups/move/{sourceGroupId}/{destinationGroupId}/affected-users:
    $ref: paths/affected-users.yaml
  /user-admin/groups/{groupId}:
    $ref: paths/group.yaml
