openapi: 3.0.0
info:
  title: Roles
  version: v2
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /user-admin/roles:
    $ref: paths/roles.yaml
  /user-admin/roles/grantable-roles:
    $ref: paths/grantable-roles.yaml
  /user-admin/roles/{roleId}:
    $ref: paths/role.yaml
