openapi: 3.0.0
info:
  title: Roles
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-roles-api.yaml
paths:
  /user-admin/roles:
    $ref: paths/roles.yaml
  /user-admin/roles/grantable-roles:
    $ref: paths/grantable-roles.yaml
  /user-admin/roles/{roleId}:
    $ref: paths/role.yaml
