openapi: 3.0.0
info:
  title: Your user profile
  version: '3'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v3
tags:
- description: |
    Manage your profile, password, or multi-factor authentication. Users
    can edit their own profiles, but only administrators can edit profiles belonging
    to other users.
  name: Profile
x-akamai:
  auth-type: EDGE_GRID
  file-path: 05-user-profile-api.yaml
paths:
  /user-profile:
    $ref: paths/user-profile.yaml
  /user-profile/additionalAuthentication:
    $ref: paths/additional-authentication-profile.yaml
  /user-profile/additionalAuthentication/reset:
    $ref: paths/reset-auth-profile.yaml
  /user-profile/basic-info:
    $ref: paths/basic-info-profile.yaml
  /user-profile/change-password:
    $ref: paths/change-password.yaml
  /user-profile/notifications:
    $ref: paths/notifications-profile.yaml
