openapi: 3.0.0
info:
  title: Common resources, for administrators
  version: '3'
servers:
- url: https://{hostname}/identity-management/v3
tags:
- description: |
    List contact types you can use when creating a user account.
  name: Contact types
- description: |
    List locale information you can use when creating a user account.
  name: Locale
- description: |
    List products information you can use when creating a user account.
  name: Products
- description: |
    List policies you can use when creating a user account.
  name: Policies
x-akamai:
  auth-type: EDGE_GRID
paths:
  /user-admin/common/contact-types:
    $ref: paths/contact-types-admin.yaml
  /user-admin/common/countries:
    $ref: paths/countries-admin.yaml
  /user-admin/common/countries/{country}/states:
    $ref: paths/states-admin.yaml
  /user-admin/common/notification-products:
    $ref: paths/notification-products-admin.yaml
  /user-admin/common/password-policy:
    $ref: paths/password-policy-admin.yaml
  /user-admin/common/supported-languages:
    $ref: paths/supported-languages-admin.yaml
  /user-admin/common/timeout-policies:
    $ref: paths/timeout-policies-admin.yaml
  /user-admin/common/timezones:
    $ref: paths/timezones-admin.yaml
