openapi: 3.0.0
info:
  title: Common resources, for users
  version: v2
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /user-profile/common/contact-types:
    $ref: paths/contact-types-user-profile.yaml
  /user-profile/common/countries:
    $ref: paths/countries-user-profile.yaml
  /user-profile/common/countries/{country}/states:
    $ref: paths/states-user-profile.yaml
  /user-profile/common/notification-products:
    $ref: paths/notification-products-user-profile.yaml
  /user-profile/common/password-policy:
    $ref: paths/password-policy-user-profile.yaml
  /user-profile/common/supported-languages:
    $ref: paths/supported-languages-user-profile.yaml
  /user-profile/common/timeout-policies:
    $ref: paths/timeout-policies-user-profile.yaml
  /user-profile/common/timezones:
    $ref: paths/timezones-user-profile.yaml
