openapi: 3.0.0
info:
  title: IP access control lists
  version: '3'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v3
tags:
- description: |
    Manage the CIDR blocks in your account's allowlist.
  name: CIDR blocks
- description: |
    Manage the IP allowlist for an account.
  name: IP allowlists
x-akamai:
  auth-type: EDGE_GRID
  file-path: 08-ip-acl.yaml
paths:
  /user-admin/ip-acl/allowlist:
    $ref: paths/cidr-blocks.yaml
  /user-admin/ip-acl/allowlist/disable:
    $ref: paths/disable.yaml
  /user-admin/ip-acl/allowlist/enable:
    $ref: paths/enable.yaml
  /user-admin/ip-acl/allowlist/status:
    $ref: paths/status.yaml
  /user-admin/ip-acl/allowlist/validate:
    $ref: paths/validate.yaml
  /user-admin/ip-acl/allowlist/{cidrBlockId}:
    $ref: paths/cidr-block.yaml
