openapi: 3.0.0
info:
  title: Credentials
  version: v2
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /api-clients/self:
    $ref: paths/self.yaml
  /api-clients/self/account-switch-keys:
    $ref: paths/account-switch-keys-self.yaml
  /api-clients/self/credentials:
    $ref: paths/credentials-self.yaml
  /api-clients/self/credentials/deactivate:
    $ref: paths/credentials-self-deactivate.yaml
  /api-clients/self/credentials/{credentialId}:
    $ref: paths/credential-self.yaml
  /api-clients/self/credentials/{credentialId}/deactivate:
    $ref: paths/credential-self-deactivate.yaml
  /api-clients/{clientId}:
    $ref: paths/client.yaml
  /api-clients/{clientId}/account-switch-keys:
    $ref: paths/account-switch-keys-client.yaml
  /api-clients/{clientId}/credentials:
    $ref: paths/credentials-client.yaml
  /api-clients/{clientId}/credentials/deactivate:
    $ref: paths/credentials-client-deactivate.yaml
  /api-clients/{clientId}/credentials/{credentialId}:
    $ref: paths/credential-client.yaml
  /api-clients/{clientId}/credentials/{credentialId}/deactivate:
    $ref: paths/credential-client-deactivate.yaml
