openapi: 3.0.0
info:
  title: API client credentials
  version: '3'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v3
x-akamai:
  auth-type: EDGE_GRID
  file-path: 10-api-clients-credentials.yaml
paths:
  /api-clients/self/credentials:
    $ref: paths/credentials-self.yaml
  /api-clients/self/credentials/deactivate:
    $ref: paths/deactivate-credentials-self.yaml
  /api-clients/self/credentials/{credentialId}:
    $ref: paths/credential-self.yaml
  /api-clients/self/credentials/{credentialId}/deactivate:
    $ref: paths/deactivate-credential-self.yaml
  /api-clients/{clientId}/credentials:
    $ref: paths/credentials-client.yaml
  /api-clients/{clientId}/credentials/deactivate:
    $ref: paths/deactivate-credentials-client.yaml
  /api-clients/{clientId}/credentials/{credentialId}:
    $ref: paths/credential-client.yaml
  /api-clients/{clientId}/credentials/{credentialId}/deactivate:
    $ref: paths/deactivate-credential-client.yaml
