type: object
description: |-
  Returns a social login application.
  
x-akamai:
  file-path: schemas/view-social-login-application.yaml
additionalProperties: false
required:
- appid
- createdAt
- providers
- realm
- secret
- updatedAt
properties:
  _links:
    type: object
    description: |
      Navigable hypermedia links for the custom providers.
    additionalProperties: false
    required:
    - custom-providers
    properties:
      custom-providers:
        type: object
        description: |
          Navigable hypermedia links for the custom providers.
        additionalProperties: false
        required:
        - href
        properties:
          href:
            type: string
            description: |
              Hypermedia link for the application's custom providers.
            minLength: 1
      self:
        type: object
        description: |
          Navigable hypermedia links for the social login application.
        additionalProperties: false
        required:
        - href
        properties:
          href:
            type: string
            description: |
              Navigable hypermedia link to a social login application.
            minLength: 1
  allowedTokenDomainPatterns:
    type: array
    description: |
      Domains that can communicate with the social login application. If `null`, any domain can communicate with your social login application.
    nullable: true
    minItems: 0
    items:
      type: string
      minLength: 1
  appid:
    type: string
    description: |
      Unique identifier of a social login application.
    minLength: 1
  createdAt:
    type: string
    description: |
      Timestamp indicating the creation date for the social login application.
    format: date-time
  customerid:
    type: string
    description: |
      Unique identifier your organization. Akamai issues you a customer ID when you subscribe to Identity Cloud.
    minLength: 1
  enabledProviders:
    type: array
    description: |
      Social login providers ready for immediate use. If `null`, no providers are available for immediate use.
    nullable: true
    minItems: 0
    items:
      type: string
      minLength: 1
  providers:
    type: array
    description: |
      Available social login providers, including those not yet ready for use. If `null`, the application doesn't have any social login providers'.
    nullable: true
    minItems: 0
    items:
      type: string
      minLength: 1
  realm:
    type: string
    description: |
      Authentication domain for a social login application. Unless you use a custom domain, your social login applications are typically on the `rpxnow.com` domain. In that case, and if your domain is `my-domain.rpxnow.com`, your realm is `my-domain`.
    minLength: 1
  secret:
    type: string
    description: |
      Password for the social login application.
    minLength: 1
  updatedAt:
    type: string
    description: |
      Timestamp indicating the last update time for the social login application.
    format: date-time
