openapi: 3.0.0
info:
  title: Tags
  version: v3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/events/v3
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-tags.yaml
paths:
  /tags:
    $ref: paths/tags.yaml
