openapi: 3.0.0
info:
  title: Access control lists
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/network-cloud-firewall/v1
- url: http://network-cloud-firewall/v1
tags:
- description: |
    Manage ACL aliases used within ACL rules.
  name: ACL aliases
- description: |
    Manage ACL rules, which define the traffic allowed through the Network Cloud Firewall.
  name: ACL rules
- description: |
    Provides the list of all the ACL rules for the version number.
  name: ACL versions
- description: |
    ACL source IP aliases with 50 entries or more.
  name: Big aliases
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-acls.yaml
paths:
  /acls/aliases:
    $ref: paths/acl-aliases.yaml
  /acls/aliases/{aliasId}:
    $ref: paths/acl-aliases-by-id.yaml
  /acls/big-aliases/upload:
    $ref: paths/big-aliases-upload.yaml
  /acls/big-aliases/upload/{aliasId}:
    $ref: paths/big-aliases.yaml
  /acls/ip-versions/{ipVersion}/rules/{index}:
    $ref: paths/acl-rules.yaml
  /acls/versions:
    $ref: paths/acl-versions.yaml
  /acls/versions/{version}:
    $ref: paths/acl-versions-by-id.yaml
  /acls/versions/{version}/clone:
    $ref: paths/acl-versions-clone.yaml
