openapi: 3.0.0
info:
  title: Rules
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/network-cloud-firewall/v1
- url: http://network-cloud-firewall/v1
tags:
- description: |
  View rule match statistics.
  name: Rule hits
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-rules.yaml
paths:
  /rule-hits/rules:
    $ref: paths/rule-hits.yaml
  /rule-hits/rules/{ruleId}:
    $ref: paths/rule-hits-by-id.yaml
