openapi: 3.0.0
info:
  title: Usage statistics
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/network-cloud-firewall/v1
- url: http://network-cloud-firewall/v1
tags:
- description: |
    View account limits for entitlements, aliases, and trust or block lists.
  name: Account limits
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-stats.yaml
paths:
  /stats:
    $ref: paths/account-usage.yaml
