type: object
additionalProperties: false
required:
- bocc
- cdns
- dataStreams
- origins
- arlId
nullable: true
properties:
  bocc:
    description: |
      Specify diagnostic data beacons details. It enables real time beaconing for [Broadcast Operations Control Center](https://www.akamai.com/global-services/services/broadcast-operations-command-center).
    $ref: ../schemas/Bocc.yaml
  cdns:
    type: array
    description: |
      CDNs added for the configuration.
    minItems: 1
    items:
      $ref: ../schemas/ConfigCdn.yaml
  dataStreams:
    description: |
      Specifies data streams details.
    $ref: ../schemas/DataStreams.yaml
  enableSoftAlerts:
    type: boolean
    description: |
      Option to opt out of alerts based on soft limits of bandwidth usage.
    default: false
  origins:
    type: array
    description: |
      Origins corresponding to the properties selected in the configuration.
    minItems: 1
    items:
      $ref: ../schemas/ConfigOrigin.yaml
  advancedSettings:
    description: |
      Describes advanced settings. Note that this field is available only for internal users.
    $ref: ../schemas/AdvancedSettings.yaml
  arlId:
    type: integer
    description: |
      Unique identifier for the Akamai Resource Locator.
    nullable: true
    minimum: 1
