type: object
description: |
  Cloud Wrapper configurations.
additionalProperties: false
required:
- configurations
properties:
  configurations:
    type: array
    description: |
      Cloud Wrapper configurations.
    minItems: 0
    items:
      $ref: ../schemas/Configuration.yaml
