type: object
description: |
  Creates a Cloud Wrapper configuration.
additionalProperties: false
required:
- comments
- contractId
- locations
- configName
- propertyIds
properties:
  capacityAlertsThreshold:
    type: integer
    description: |
      Capacity Alerts enablement information for the configuration.
    nullable: true
    format: int64
    minimum: 50
    maximum: 100
  comments:
    type: string
    description: |
      Additional information you provide to differentiate or track changes of the configuration.
    minLength: 1
    maxLength: 255
  contractId:
    type: string
    description: |
      Contract ID having Cloud Wrapper entitlement.
    minLength: 0
    maxLength: 20
    pattern: ^[A-Za-z0-9-_.]*$
  locations:
    type: array
    description: |
      Locations to use with the configuration. Locations need to have a pre-approved capacity approval for the selected contract.
    minItems: 1
    maxItems: 2147483647
    items:
      $ref: ../schemas/ConfigLocation.yaml
  multiCdnSettings:
    description: |
      Specify details about the Multi CDN settings.
    $ref: ../schemas/ConfigMultiCdnSettings.yaml
  configName:
    type: string
    description: |
      The name of the configuration (property) you've set up to deliver your content. This is the `propertyName` you set when you [create](https://techdocs.akamai.com/property-mgr/reference/post-properties) the property.
    minLength: 4
    maxLength: 20
    pattern: '[A-Za-z0-9-]*$'
  notificationEmails:
    type: array
    description: |
      Email addresses to use for notifications.
    minItems: 0
    items:
      type: string
      format: email
  propertyIds:
    type: array
    description: |
      Identifiers for [properties](ref:concepts) eligible to add Cloud Wrapper. To see property specifics, run the [list properties](ref:get-properties) operation.
    minItems: 1
    items:
      type: string
      minLength: 1
      maxLength: 1000000000
  retainIdleObjects:
    type: boolean
    description: |
      By default, idle objects are kept in your footprint for 30 days. Set this to `true` to retain them beyond this 30 day limit. This only applies to [locations](ref:get-locations) you've configured with a redundant content `type` like `LIVE_VOD` or `WEB_STANDARD_TLS`.
    default: false
