openapi: 3.0.0
info:
  title: Live Archive Management
  version: '1.0'
servers:
- url: https://{hostname}/live-archive/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /streams/{streamId}/archives:
    $ref: paths/archives.yaml
  /streams/{streamId}/endpoints:
    $ref: paths/endpoints.yaml
  /streams/{streamId}/endpoints/{endpoint}:
    $ref: paths/endpoint.yaml
  /vod:
    $ref: paths/vod.yaml
  /vod/{EID}:
    $ref: paths/eid.yaml
