openapi: 3.0.0
info:
  title: Key collections
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/jwt-api/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-key-collections.yaml
paths:
  /key-collections:
    $ref: paths/key-collections.yaml
  /key-collections/{collectionId}:
    $ref: paths/collection.yaml
  /key-collections/{collectionId}/versions:
    $ref: paths/versions.yaml
  /key-collections/{collectionId}/versions/{versionId}:
    $ref: paths/version.yaml
