openapi: 3.0.0
info:
  title: Activations
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/jwt-api/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-activations.yaml
paths:
  /activations:
    $ref: paths/activations.yaml
