type: object
description: |
  The end time for report data, in epoch seconds.
additionalProperties: false
required:
- endTimeSec
minLength: 1
properties:
  endTimeSec:
    type: integer
    description: |
      The end time for report data, in epoch seconds.
    minimum: 0
