openapi: 3.0.0
info:
  title: Enrollments
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/cps/v2
tags:
- description: |
    Manage your certificate enrollments.
  name: Enrollments
- description: |
    Manage your certificate deployments.
  name: Deployments
- description: |
    Manage changes to an enrollment's network deployment.
  name: Changes
- description: |
    Get information on your certificates.
  name: Certificates
x-akamai:
  auth-type: EDGE_GRID
  file-path: enrollments.yaml
paths:
  /active-certificates:
    $ref: paths/active-certificates.yaml
  /enrollments:
    $ref: paths/enrollments.yaml
  /enrollments/{enrollmentId}:
    $ref: paths/enrollment.yaml
  /enrollments/{enrollmentId}/changes/{changeId}:
    $ref: paths/change.yaml
  /enrollments/{enrollmentId}/changes/{changeId}/deployment-schedule:
    $ref: paths/deployment-schedule.yaml
  /enrollments/{enrollmentId}/changes/{changeId}/input/info/{allowedInputTypeParam}:
    $ref: paths/allowed-input-type.yaml
  /enrollments/{enrollmentId}/changes/{changeId}/input/update/{allowedInputTypeParam}:
    $ref: paths/allowed-input-type-update.yaml
  /enrollments/{enrollmentId}/deployments:
    $ref: paths/deployments.yaml
  /enrollments/{enrollmentId}/deployments/production:
    $ref: paths/production.yaml
  /enrollments/{enrollmentId}/deployments/staging:
    $ref: paths/staging.yaml
  /enrollments/{enrollmentId}/dv-history:
    $ref: paths/dv-history.yaml
  /enrollments/{enrollmentId}/history/certificates:
    $ref: paths/certificates.yaml
  /enrollments/{enrollmentId}/history/changes:
    $ref: paths/changes.yaml
