openapi: 3.0.0
info:
  title: Insights
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/script-management/v1
tags:
- description: Groups operations that you can use to get details about script performance.
  name: Insights
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-insights.yaml
paths:
  /properties/{propertyId}/hostnames/{hostname}/network/{network}/insights:
    $ref: paths/insights.yaml
