type: array
description: |
  The application service settings. 
x-akamai:
  file-path: schemas/appconfigversion-service-data.yaml
items:
  type: object
  additionalProperties: false
  properties:
    name:
      type: string
      description: |
        A unique name for the service.
    rules:
      type: array
      description: |
        The risk assessment rules applied to the service.
      nullable: true
      items:
        type: string
    service_type:
      type: integer
      description: |
        The service type. Either `1` for WAF, `2` for Acceleration, `3` for ICAP, `4` for IPS, `5` for SLB, `6` for access control, `7` for rewrite, or `8` for group rewrite.
      default: 1
      enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    settings:
      type: array
      description: |
        Service settings.
      items:
        type: object
        additionalProperties: false
        properties:
          name:
            type: string
            description: |
              The service setting name.
          value:
            type: string
            description: |
              The service setting value.
          setting_type:
            type: integer
            description: |
              The service setting type. 
    status:
      type: integer
      description: |
        The service status. Either `0` for off or `1` for on. 
      enum:
      - 0
      - 1
