type: object
description: |-
  Application config version advanced settings.
  
x-akamai:
  file-path: schemas/appconfigversion-advanced-settings.yaml
additionalProperties: false
properties:
  acceleration:
    type: string
    description: |
      Enables traffic acceleration for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  allow_cors:
    type: string
    description: |
      Allows cross-origin resource sharing between domains. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  anonymous_server_conn_limit:
    type: string
    description: |
      The maximum number of concurrent anonymous server connections.
  anonymous_server_request_limit:
    type: string
    description: |
      The maximum number of concurrent anonymous server requests.
  app_auth:
    type: string
    description: |
      The application-facing authentication mechanism. Default is `none`.
  app_auth_domain:
    type: string
    description: |
      Specifies the active directory domain where the application's service account was created. Used if the application supports Kerberos. Specify `null` if you want to provide this later.
    nullable: true
  app_client_cert_auth:
    type: string
    description: |
      Enables client certificate authentication. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  app_cookie_domain:
    type: string
    description: |
      The domain to be used in application cookies. Specify `null` if you want to provide this later.
    nullable: true
  app_location:
    type: string
    description: |
      The application's location. Specify `null` if you want to provide this later.
    nullable: true
  app_server_read_timeout:
    type: string
    description: |
      The maximum time for an application server to fulfill a user request. The default is 60 seconds.
  authenticated_server_conn_limit:
    type: string
    description: |
      The maximum number of authenticated server connections allowed.
  authenticated_server_request_limit:
    type: string
    description: |
      The maximum number of authenticated server connections allowed.
  client_cert_auth:
    type: string
    description: |
      Enables client certificate authorization. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  client_cert_user_param:
    type: string
    description: |
      Relevant certificate parameters for client authentication.
  cookie_domain:
    type: string
    description: |
      The domain to use for cookies if your application uses iFrames. Specify `null` if you want to provide this later.
  cors_header_list:
    type: string
    description: |
      Controls which origins are populated in the `Access-Control-Allow-Origin`` header. Defaults to `unbounded`, which echoes back the value of the `Origin` header which was sent by the browser.
    default: unbounded
  cors_max_age:
    type: string
    description: |
      "The maximum time in seconds that can lapse before preflight information expires. After this time a new preflight
      request needs to be made for an unsafe request. \n"
  cors_method_list:
    type: string
    description: |
      Controls which HTTP methods are populated in the `Access-Control-Allow-Methods` header in response to a preflight request.
  cors_origin_list:
    type: string
    description: |
      Controls which origins are populated in the `Access-Control-Allow-Origin` header. The default value of `unbounded` echoes back the value of the `Origin` header sent by the browser.
  cors_support_credential:
    type: string
    description: |
      Enables the application to respond with the `Access-Control-Allow-Credentials: true` header set. Either `on` or `off`. If `off`, authentication between applications fails. If a cookie is sent to a cross-origin and the response does not include this header, the browser ignores the response. Either `off` or `on`.
    enum:
    - off
    - on
  custom_headers:
    type: array
    description: |
      Custom headers for application connections.
    items:
      type: string
      nullable: true
  domain_exception_list:
    type: string
    description: |
      A list of domains to except from content rewrite. 
  edge_authentication_enabled:
    type: string
    description: |
      Enables edge authentication for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  edge_cookie_key:
    type: string
    description: |
      The edge key to share with your ION configuration.
  external_cookie_domain:
    type: string
    description: |
      The external domain to use for cookies if your application uses iFrames. Specify `null` if you want to provide this later.
    nullable: true
  force_mfa:
    type: string
    description: |
      Forces multi-factor authentication. Either `off` or `on`.
    enum:
    - on
    - off
  forward_ticket_granting_ticket:
    type: string
    description: |
      Enables Kerberos forward ticket grants, instead of using a keytab file. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  g2o_enabled:
    type: string
    description: |
      Enables G2O on an application configuration. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  g2o_key:
    type: string
    description: |
      The G2O key to share with your ION configuration.
    nullable: true
  g2o_nonce:
    type: string
    description: |
      The G2O nonce to share with your ION configuration.
    nullable: true
  health_check_fall:
    type: string
    description: |
      The number of consecutive missed heartbeats before the connector considers an application server to be unreachable.
  health_check_http_host_header:
    type: string
    description: |
      The host header to use for HTTP health checks.
    nullable: true
  health_check_http_url:
    type: string
    description: |
      The URL to use for HTTP health checks.
  health_check_http_version:
    type: string
    description: |
      The HTTP version to use for the health check.
  health_check_interval:
    type: string
    description: |
      The interval between successive heartbeats in seconds.
  health_check_rise:
    type: string
    description: |
      The number of consecutive successful heartbeats that connectors need to receive before considering an application server to be healthy. The default is two.
  health_check_timeout:
    type: string
    description: |
      The time in seconds that the connector waits before considering a heartbeat attempt to have failed.
  health_check_type:
    type: string
    description: |
      The type of health check to perform on all the associated servers to verify service availability. Either `0` for default, `1` for http, `2` for https, `3` for tls, `4` for sslv3, `5` for `6` for tcp, or `7` for disable.
    enum:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
  hidden_app:
    type: string
    description: |
      Used to hide the application from the login portal. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  host_key:
    type: string
    description: |
      The host secret key.
    nullable: true
  hsts_age:
    type: string
    description: |
      The maximum age of the HTTP Strict Transport Security activity period, in seconds.
  http_only_cookie:
    type: string
    description: |
      Indicates whether cookies created for this application are only used for HTTP content. If your application uses a Java applet, you may want to disable this option. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  https_sslv3:
    type: string
    description: |
      Enables the application to interact with the connector using SSLv3. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  idle_close_time_seconds:
    type: string
    description: |
      The number of seconds a session may remain idle before it's closed.
  idle_conn_ceil:
    type: string
    description: |
      The maximum number of user access TLS sessions to applications pre-created by a given connector.
  idle_conn_floor:
    type: string
    description: |
      The minimum number of user access TLS sessions to applications pre-created by a given connector.
  idle_conn_step:
    type: string
    description: |
      The incremental number of user access TLS sessions to launch for applications by a given connector.
  idp_idle_expiry:
    type: string
    description: |
      The number of seconds before an idle session with the IDP expires. Specify `null` if you want to provide this later.
    nullable: true
  idp_max_expiry:
    type: string
    description: |
      The maximum number of seconds to maintain an IDP session. Specify `null` if you want to provide this later.
    nullable: true
  ignore_bypass_mfa:
    type: string
    description: |
      Ignores MFA bypass attempts on the application. Either `off` or `on`.
    enum:
    - off
    - on
  ignore_cname_resolution:
    type: string
    description: |
      Ignore CNAME DNS resolutions for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  inject_ajax_javascript:
    type: string
    description: |
      Enables custom JavaScript injection when rewriting websocket and XHR requests. Either `off` or `on`.
    enum:
    - off
    - on
  internal_host_port:
    type: string
    description: |
      The internal host port to perform CNAME redirection on. Specify `null` if not applicable.
  internal_hostname:
    type: string
    description: |
      The internal hostname to perform CNAME redirection on. Specify `null` if not applicable.
    nullable: true
  ip_access_allow:
    type: string
    description: |
      Allows access to IP based applications hosted in internal networks though EAA Client connector. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  is_ssl_verification_enabled:
    type: string
    description: |
      Indicates if SSL verification is enabled for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  keepalive_connection_pool:
    type: string
    description: |
      The maximum number of connections allowed in the keepalive pool.
  keepalive_enable:
    type: string
    description: |
      Enables connection keepalives. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  keepalive_timeout:
    type: string
    description: |
      The keepalive timeout period in seconds.
  kerberos_negotiate_once:
    type: string
    description: |
      Configures the application to perform Kerberos authentication only on the initial login URL. Either `on` or `off`.
  keyed_keepalive_enable:
    type: string
    description: |
      Allows a connection between two devices to remain open, even when no data is being transmitted. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  keytab:
    type: string
    description: |
      A unique keytab for Kerberos delegation.
  load_balancing_metric:
    type: string
    description: |
      The load-balancing metric for the application. Either `round-robin` or `ip-hash`.
    enum:
    - round-robin
    - ip-hash
  logging_enabled:
    type: string
    description: |
      Enables logging for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  login_timeout:
    type: string
    description: |
      The number of seconds before a login attempt times out.
  login_url:
    type: string
    description: |
      The URL for which authentication tokens need to be generated. Specify `null` if not applicable.
    nullable: true
  logout_url:
    type: string
    description: |
      The single-sign out URL triggered when a user logs out of an SSO application. Specify `null` if not applicable.
    nullable: true
  mdc_enable:
    type: string
    description: |
      Enables multi-data center connections. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  mfa:
    type: string
    description: |
      Enables multi-factor authentication for the application. Either `enable`, `disable`, or `inherit`.
    enum:
    - enable
    - disable
    - inherit
  offload_onpremise_traffic:
    type: string
    description: |
      Enables on-premises users to bypass the EAA cloud to access applications. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  pass_phrase:
    type: string
    description: |
      The passphrase for the certificate. 
    nullable: true
  preauth_consent:
    type: string
    description: |
      Enables consent for OIDC pre-authorization. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  preauth_enforce_url:
    type: string
    description: |
      The URL that users are directed to when authenticating with a third party IdP. By default users are directed to the EAA application page.
  private_key:
    type: string
    description: |
      Private key for the certificate.
    nullable: true
  proxy_buffer_size_kb:
    type: string
    description: |
      The size of the proxy's buffer, in kilobytes.
    nullable: true
  proxy_disable_clipboard:
    type: string
    description: |
      Prevents users from copying information from a RDP session. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  rate_limit:
    type: string
    description: |
      Enables rate limiting for the application. Either `on` or `off`.
    enum:
    - on
    - off
  rdp_initial_program:
    type: string
    description: |
      The program that initializes when the user logs in to the remote environment. Specify `null` if not applicable.
    nullable: true
  rdp_legacy_mode:
    type: string
    description: |
      Enables legacy mode RDP connections to the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  rdp_remote_apps:
    type: array
    description: |
      Remote RDP applications. 
    items:
      type: string
      nullable: true
  rdp_tls1:
    type: string
    description: |
      Enables TLS v1 for RDP connections. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  refresh_sticky_cookie:
    type: string
    description: |
      Enables refresh of cookies used for session stickiness. Either `on` or `off`.
    enum:
    - off
    - on
  remote_spark_audio:
    type: string
    description: |
      Enables audio integration for Cisco Webex Spark application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  remote_spark_disk:
    type: string
    description: |
      Name of the disk for Cisco Webex Spark application.
  remote_spark_mapClipboard:
    type: string
    description: |
      Enables map clipboard integration for Cisco Webex Spark application. Either `on` or `off`.
    enum:
    - on
    - off
  remote_spark_mapDisk:
    type: string
    description: |
      Enables map disk integration for Cisco Webex Spark application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  remote_spark_mapPrinter:
    type: string
    description: |
      Enables map printer integration for Cisco Webex Spark application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  remote_spark_printer:
    type: string
    description: |
      Name of the printer for Cisco Webex Spark application.
  remote_spark_recording:
    type: string
    description: |
      Enables recording integration for Cisco Webex Spark application. Either `true` or `false`. 
    enum:
    - 'true'
    - 'false'
  request_body_rewrite:
    type: string
    description: |
      Enables the application to rewrite request body data. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  request_parameters:
    type: string
    description: |
      The HTTP request parameter to use. For example, `GET`. Specify `null` if not applicable.
    nullable: true
  saas_enabled:
    type: string
    description: |
      Enables SaaS for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  sentry_redirect_401:
    type: string
    description: |
      Enables the Sentry module to redirect requests that receive a 401 response.
  server_cert_validate:
    type: string
    description: |
      Enables EAA to fo origin server certification validation for HTTPS applications. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  server_request_burst:
    type: string
    description: |
      The server request threshold for burst monitoring.
  service_principle_name:
    type: string
    description: |
      The application's Kerberos service principal name (SPN). If your application uses a different service principal name, specify the configuration suitable for your application. Specify `null` if not applicable.
    nullable: true
  session_sticky:
    type: string
    description: |
      Enables session stickiness to ensure that a given session always traverses the same connector when interacting with the application. Either `true` or `false`. Specify `null` if not applicable.
    nullable: true
    enum:
    - 'true'
    - 'false'
  session_sticky_cookie_maxage:
    type: string
    description: |
      Sets the maximum age in seconds for the session stickiness cookie.
  session_sticky_server_cookie:
    type: string
    description: |
      Enables refresh of a sticky cookie to ensure that the content goes to the same connector to prevent session lag or content loss in a session, even after the session length has passed. Omit it if not applicable, and the value subsequently reflects back as `null`.
    nullable: true
  single_host_content_rw:
    type: string
    description: |
      Enables single host content rewrite. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  single_host_cookie_domain:
    type: string
    description: |
      Enables single host cookie domains. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  single_host_enable:
    type: string
    description: |
      Enables single host FQDN for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  single_host_fqdn:
    type: string
    description: |
      The single host fully qualified domain name used to host multiple applications.
  single_host_path:
    type: string
    description: |
      The single host path used to host multiple applications.
  sla_object_url:
    type: string
    description: |
      The SLA object URL to share with your ION configuration.
  spdy_enabled:
    type: string
    description: |
      Enables SPDY traffic management. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  ssh_audit_enabled:
    type: string
    description: |
      Enables ssh session auditing. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  sso:
    type: string
    description: |
      Enables SSO authentication for the application. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  sticky_agent:
    type: string
    description: |
      Enables connector persistence for connections. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  user_name:
    type: string
    description: |
      The username to use for application authentication. Specify `null` if not applicable.
    nullable: true
  wapp_auth:
    type: string
    description: |
      The authentication method for the application. Either `form`, `basic`, `basic+cookie`, or `certificate_only`.
    enum:
    - form
    - basic
    - basic+cookie
    - certificate_only
  websocket_enabled:
    type: string
    description: |
      Indicates that this application uses WebSockets for HTTP transport. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
  wildcard_internal_hostname:
    type: string
    description: |
      Enables an optional wildcard string for internal hostnames. Either `true` or `false`.
    enum:
    - 'true'
    - 'false'
