type: object
description: |-
  Application names configuration.
  
x-akamai:
  file-path: schemas/appconfigversion-names.yaml
additionalProperties: false
properties:
  cert_name:
    type: string
    description: |
      A descriptive name for the certificate.
  connector_names:
    type: object
    description: |
      The connector names.
  directory_names:
    type: object
    description: |
      Directory IDs and their names. 
    additionalProperties:
      type: string
      description: |
        Directory ID and name pairings.
  domain_suffix:
    type: string
    description: |
      The suffix to add to all hostnames.
  group_names:
    type: object
    description: |
      Group IDs and their names. 
    additionalProperties:
      type: string
      description: |
        Group ID and name pairings.
  idp_name:
    type: string
    description: |
      The IdP name.
  pop_name:
    type: string
    description: |
      The POP name.
  ssl_ca_cert:
    type: string
    description: |
      The CA-signed SSL certificate contents.
