type: object
description: |
  Enterprise access groups for an application.
additionalProperties: false
required:
- meta
- objects
properties:
  meta:
    $ref: pageable.yaml
  objects:
    type: array
    description: |
      Application access group details.
    minItems: 1
    items:
      $ref: application-group.yaml
