type: object
description: |
  Enterprise Access services for an application.
additionalProperties: false
required:
- meta
- objects
properties:
  meta:
    $ref: pageable.yaml
  objects:
    type: array
    description: |
      EAA application service details.
    minItems: 1
    items:
      $ref: application-service.yaml
