type: object
description: |
  List of Enterprise Access Applications.
additionalProperties: false
required:
- meta
- objects
properties:
  meta:
    $ref: pageable.yaml
  objects:
    type: array
    description: |
      List of applications for the account.
    minItems: 1
    items:
      $ref: application.yaml
