type: array
description: |-
  Target connectors for deploying the application configuration.
  
x-akamai:
  file-path: schemas/assign-agents-application-response.yaml
items:
  type: object
  additionalProperties: false
  properties:
    agent:
      type: object
      description: |
        Connector properties for the application deployment.
      additionalProperties: false
      required:
      - name
      - uuid_url
      properties:
        name:
          type: string
          description: |
            The name of the connector.
          minLength: 1
        uuid_url:
          type: string
          description: |
            The UUID URL of the connector.
          minLength: 1
    resource_uri:
      type: object
      description: |
        Resource locations for the connector.
      additionalProperties: false
      required:
      - href
      properties:
        href:
          type: string
          description: |
            The location of connector details.
          minLength: 1
