type: array
description: |
  Custom DNS settings.
items:
  type: object
  additionalProperties: true
  required:
  - settings
  properties:
    settings:
      type: string
    custom_dns:
      type: boolean
      description: |
        Custom child DNS settings.
      default: false
