type: object
description: |-
  Multifactor authentication settings for the IDP configuration.
  
x-akamai:
  file-path: schemas/idp-mfa-settings.yaml
additionalProperties: false
properties:
  duo_akey:
    type: string
    description: |
      The Duo authentication key.
  duo_api_hostname:
    type: string
    description: |
      The hostname of the Duo API to contact for authentication.
  duo_integration_key:
    type: string
    description: |
      The unique client ID to integrate with Duo Security's MFA service.
  duo_secret_key:
    type: string
    description: |
      The secret key for Duo MFA requests.
  duo_umap:
    type: string
    description: |
      The user email used by Duo to map authentication requests.
  idp_notification_org_name:
    type: string
    description: |
      The name of the IDP authentication organization to notify.
  mfa_email_immutable:
    type: string
    description: |
      Whether the Duo email factor is immutable, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_email_preset:
    type: string
    description: |
      Whether MFA has a pre-set email address. Either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_factor_duo:
    type: string
    description: |
      Whether MFA uses Duo authentication factor, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_factor_email:
    type: string
    description: |
      Whether MFA uses email authentication factor, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_factor_sms:
    type: string
    description: |
      Whether MFA uses SMS authentication factor, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_factor_totp:
    type: string
    description: |
      Whether MFA uses Time-based One Time Password (TOTP) authentication factor, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_pci_dss:
    type: string
    description: |
      Whether MFA uses additional authentication for PCI DSS compliance, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_sms_immutable:
    type: string
    description: |
      Whether the Duo SMS factor is immutable, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
  mfa_sms_preset:
    type: string
    description: |
      Whether MFA uses an SMS verification factor, either a `true` or `false` string.
    enum:
    - 'true'
    - 'false'
