type: object
description: |-
  Application service settings.
  
x-akamai:
  file-path: schemas/service-settings.yaml
additionalProperties: false
properties:
  bad_robots:
    type: string
    description: |
      Whether to block bad robots from the service.
    minLength: 1
  compression:
    type: string
    description: |
      Compression type to use for the service.
    minLength: 1
  http_policy:
    type: string
    description: |
      Enables an HTTP policy.
    minLength: 1
  icap_file_size:
    type: string
    description: |
      Internet Content Adaptation Protocol maximum file size in Megabytes. The default is 500.
  icap_file_size_allow:
    type: string
    description: |
      If the file exceeds the maximum file size, select either `deny` to reject the file transfer or `ignore`.
    enum:
    - deny
    - ignore
  icap_hc_type:
    type: string
    description: |
      ICAP health check type. Either `icap` or `tcp`.
    enum:
    - icap
    - tcp
  icap_host:
    type: string
    description: |
      Host or IP address of the co-located ICAP server to use with EAA.
    minLength: 1
  icap_http_methods:
    type: string
    description: |
      HTTP method used to forward traffic to the ICAP server.
    default: POST
    minLength: 1
  icap_mime_types:
    type: string
    description: |
      MIME types to allow for forwarding to the ICAP server.
    minLength: 1
  icap_port:
    type: integer
    description: |
      Port number to communicate with the ICAP server.
    minimum: 1
  icap_service:
    type: string
    description: |
      A descriptive name for the service using ICAP.
    minLength: 1
  icap_tls_enable:
    type: string
    description: |
      Enables TLS for the service.
    minLength: 1
  illegal_resource_access:
    type: string
    description: |
      Logs illegal resource access attempts. `Off` by default.
    minLength: 1
  joomla:
    type: string
    description: |
      Allows Joomla traffic. `Off` by default.
    minLength: 1
  php:
    type: string
    description: |
      Allows PHP traffic. `Off` by default.
    minLength: 1
  protocol_anomalies:
    type: string
    description: |
      Logs protocol anomalies. `Off` by default.
    minLength: 1
  protocol_violations:
    type: string
    description: |
      Logs protocol violations. `Off` by default.
    minLength: 1
  request_limits:
    type: string
    description: |
      Enables request limits. `Off` by default.
    minLength: 1
  sql_injection:
    type: string
    description: |
      Allows SQL injection traffic. `Off` by default.
    minLength: 1
  wordpress:
    type: string
    description: |
      Allows Wordpress traffic. `Off` by default.
    minLength: 1
  xss_attack:
    type: string
    description: |
      Logs cross-site scripting attack attempts. `Off` by default.
    minLength: 1
