openapi: 3.0.1
info:
  title: CloudWrapper Locations
  version: v1
servers:
- url: https://{hostname}/cloud-wrapper/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /locations:
    get:
      operationId: get-locations
      summary: List locations
      tags:
      - Locations
      description: |
        View the locations available to distribute your Cloud Wrapper capacity. This operation lists the available `trafficTypeId` values for use when creating configurations.
      responses:
        200:
          description: |
            The response lists available locations.
          content:
            application/json:
              example:
                $ref: examples/LocationExample.json
              schema:
                $ref: schemas/Locations.yaml
        400:
          $ref: errors/400.yaml
        401:
          $ref: errors/401.yaml
        403:
          $ref: errors/403.yaml
        404:
          $ref: errors/404.yaml
        405:
          $ref: errors/405.yaml
        500:
          $ref: errors/500.yaml
