openapi: 3.0.0
info:
  title: Adaptive Media Delivery
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-delivery-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-adaptive-media-delivery.yaml
paths:
  /adaptive-media-delivery/data:
    $ref: paths/data-adaptive-media-delivery.yaml
  /adaptive-media-delivery/data-stores:
    $ref: paths/data-stores-adaptive-media-delivery.yaml
  /adaptive-media-delivery/data-stores/{dataStoreId}:
    $ref: paths/data-store-adaptive-media-delivery.yaml
  /adaptive-media-delivery/realtime-data:
    $ref: paths/realtime-data-adaptive-media-delivery.yaml
