openapi: 3.0.0
info:
  title: Akamai Cloud Embed (formerly Wholesale Delivery)
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-delivery-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-wholesale-delivery.yaml
paths:
  /wholesale-delivery/data:
    $ref: paths/data-wholesale-delivery.yaml
  /wholesale-delivery/data-stores:
    $ref: paths/data-stores-wholesale-delivery.yaml
  /wholesale-delivery/data-stores/{dataStoreId}:
    $ref: paths/data-store-wholesale-delivery.yaml
  /wholesale-delivery/data/realtime:
    $ref: paths/realtime-data-wholesale-delivery.yaml
