openapi: 3.0.0
info:
  title: Download Delivery
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-delivery-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-download-delivery.yaml
paths:
  /download-delivery/data:
    $ref: paths/data-download-delivery.yaml
  /download-delivery/data-stores:
    $ref: paths/data-stores-download-delivery.yaml
  /download-delivery/data-stores/{dataStoreId}:
    $ref: paths/data-store-download-delivery.yaml
  /download-delivery/realtime-data:
    $ref: paths/realtime-data-download-delivery.yaml
