openapi: 3.0.0
info:
  title: Object Delivery
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-delivery-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 04-object-delivery.yaml
paths:
  /object-delivery/data:
    $ref: paths/data-object-delivery.yaml
  /object-delivery/data-stores:
    $ref: paths/data-stores-object-delivery.yaml
  /object-delivery/data-stores/{dataStoreId}:
    $ref: paths/data-store-object-delivery.yaml
