openapi: 3.0.0
info:
  title: HTTP Content Delivery
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-delivery-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 05-delivery-content-delivery.yaml
paths:
  /delivery/httpcd/data:
    $ref: paths/data-httpcd.yaml
  /delivery/httpcd/data-stores:
    $ref: paths/data-stores-httpcd.yaml
  /delivery/httpcd/data-stores/{dataStoreId}:
    $ref: paths/data-store-httpcd.yaml
  /delivery/httpcd/dimensions:
    $ref: paths/dimensions-httpcd.yaml
  /delivery/httpcd/metrics:
    $ref: paths/metrics-httpcd.yaml
