openapi: 3.0.0
info:
  title: HTTP Downloads/File Downloads
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-delivery-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 06-delivery-file-download.yaml
paths:
  /delivery/httpdl/data:
    $ref: paths/data-httpdl.yaml
  /delivery/httpdl/data-stores:
    $ref: paths/data-stores-httpdl.yaml
  /delivery/httpdl/data-stores/{dataStoreId}:
    $ref: paths/data-store-httpdl.yaml
  /delivery/httpdl/dimensions:
    $ref: paths/dimensions-httpdl.yaml
  /delivery/httpdl/metrics:
    $ref: paths/metrics-httpdl.yaml
