openapi: 3.0.0
info:
  title: Object Caching
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/media-delivery-reports/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: 07-delivery-object-caching.yaml
paths:
  /delivery/ocp/data:
    $ref: paths/data-ocp.yaml
  /delivery/ocp/data-stores:
    $ref: paths/data-stores-ocp.yaml
  /delivery/ocp/data-stores/{dataStoreId}:
    $ref: paths/data-store-ocp.yaml
  /delivery/ocp/dimensions:
    $ref: paths/dimensions-ocp.yaml
  /delivery/ocp/metrics:
    $ref: paths/metrics-ocp.yaml
