openapi: 3.0.0
info:
  title: Reports
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/reporting-api/v1
tags:
- description: Get information about the different kinds of reports available.
  name: Report types
- description: Run reports to determine how your Akamai service is performing.
  name: Reports
x-akamai:
  auth-type: EDGE_GRID
  file-path: reports-executor.yaml
paths:
  /reports:
    $ref: paths/reports.yaml
  /reports/{name}/versions:
    $ref: paths/versions.yaml
  /reports/{name}/versions/{version}:
    $ref: paths/version.yaml
  /reports/{name}/versions/{version}/report-data:
    $ref: paths/report.yaml
