openapi: 3.0.0
info:
  title: Configurations
  version: '1'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/client-access-control/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: configurations.yaml
paths:
  /configurations:
    $ref: paths/configurations.yaml
  /configurations/{configurationId}:
    $ref: paths/configuration.yaml
  /configurations/{configurationId}/acknowledge/{version}:
    $ref: paths/version.yaml
