openapi: 3.0.0
info:
  title: Properties
  version: '3'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v3
tags:
- description: |
    Fetch properties and includes used by an account with their details,
    including their users.
  name: Assets
- description: |
    Fetch resources used by a property or include.
  name: Resources
x-akamai:
  auth-type: EDGE_GRID
  file-path: 02-properties-api.yaml
paths:
  /user-admin/properties:
    $ref: paths/properties.yaml
  /user-admin/properties/{assetId}:
    $ref: paths/property.yaml
  /user-admin/properties/{assetId}/resources:
    $ref: paths/resources.yaml
  /user-admin/properties/{assetId}/users:
    $ref: paths/users-property.yaml
  /user-admin/properties/{assetId}/users/block:
    $ref: paths/block.yaml
