openapi: 3.0.0
info:
  title: Your user profile
  version: v2
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /user-profile:
    $ref: paths/user-profile.yaml
  /user-profile/basic-info:
    $ref: paths/basic-info-user-profile.yaml
  /user-profile/change-password:
    $ref: paths/change-password.yaml
  /user-profile/notifications:
    $ref: paths/notifications-user-profile.yaml
  /user-profile/tfa:
    $ref: paths/tfa-user-profile.yaml
