openapi: 3.0.0
info:
  title: Common resources, for administrators
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: 06-common-api.yaml
paths:
  /user-admin/common/contact-types:
    $ref: paths/contact-types-user-admin.yaml
  /user-admin/common/countries:
    $ref: paths/countries-user-admin.yaml
  /user-admin/common/countries/{country}/states:
    $ref: paths/states-user-admin.yaml
  /user-admin/common/notification-products:
    $ref: paths/notification-products-user-admin.yaml
  /user-admin/common/password-policy:
    $ref: paths/password-policy-user-admin.yaml
  /user-admin/common/supported-languages:
    $ref: paths/supported-languages-user-admin.yaml
  /user-admin/common/timeout-policies:
    $ref: paths/user-admin-timeout-policies.yaml
  /user-admin/common/timezones:
    $ref: paths/user-admin-timezones.yaml
