openapi: 3.0.0
info:
  title: Common resources, for users
  version: '3'
servers:
- url: https://{hostname}/identity-management/v3
x-akamai:
  auth-type: EDGE_GRID
paths:
  /user-profile/common/contact-types:
    $ref: paths/contact-types-profile.yaml
  /user-profile/common/countries:
    $ref: paths/countries-profile.yaml
  /user-profile/common/countries/{country}/states:
    $ref: paths/states-profile.yaml
  /user-profile/common/notification-products:
    $ref: paths/notification-products-profile.yaml
  /user-profile/common/password-policy:
    $ref: paths/password-policy-profile.yaml
  /user-profile/common/supported-languages:
    $ref: paths/supported-languages-profile.yaml
  /user-profile/common/timeout-policies:
    $ref: paths/timeout-policies-profile.yaml
  /user-profile/common/timezones:
    $ref: paths/timezones-profile.yaml
