info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Credentials
  version: '2'
openapi: 3.0.0
paths:
  /api-clients/self:
    get:
      description: 'Returns details about your API client.

        '
      operationId: get-api-clients-self
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/api-client-200.json
              schema:
                $ref: schemas/api-client.yaml
          description: 'The response returns the API client.

            '
      summary: Get your client
      tags:
      - Self
  /api-clients/self/account-switch-keys:
    get:
      description: 'The response object contains the `accountSwitchKeys` and account
        names you can access based on the permissions of your API client. Once you
        have the `accountSwitchKeys`, you can make an API call to another account.
        To learn more, see [Manage many accounts with one API client](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).

        '
      operationId: get-self-account-switch-keys
      parameters:
      - $ref: parameters/search.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-account-switch-keys.json
              schema:
                $ref: schemas/self-account-switch-keys.yaml
          description: 'The response lists account switch keys.

            '
      summary: List your account switch keys
      tags:
      - Self
  /api-clients/self/credentials:
    get:
      description: 'Returns a list of your API client''s credentials.

        '
      operationId: get-self-credentials
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credentials-200.json
              schema:
                $ref: schemas/credentials.yaml
          description: 'The response lists credentials.

            '
      summary: List your credentials
      tags:
      - Self
    post:
      description: 'Creates a new credential for your API client. Only you may create
        credentials for this client. Credentials are in `active` status at creation.
        They expire two years from their creation date. However, when the API client''s
        permissions are based on Control Center permissions, credentials expire differently
        and follow the same rotation schedule listed for user passwords on those accounts.
        Run the [Update a credential](ref:put-client-credential) operation to change
        the expiration date, description, or status. Save the values from the response,
        such as the `credentialID` for future use. This is the only time you''ll see
        the client secret. Save the credential at this time to avoid the need to create
        a new one.

        '
      operationId: post-self-credentials
      responses:
        201:
          content:
            application/json:
              example:
                $ref: examples/post-credentials-200.json
              schema:
                $ref: schemas/credential.yaml
          description: 'The response returns the created credentials.

            '
      summary: Create your credential
      tags:
      - Self
  /api-clients/self/credentials/deactivate:
    post:
      description: 'Deactivates all credentials for your API client. This doesn''t
        delete the API client or the credentials. To deactivate a single credential,
        use the [Update your credential](ref:put-self-credential) operation and set
        the status to `INACTIVE`.

        '
      operationId: post-self-credentials-deactivate
      responses:
        204:
          description: 'Credentials deactivated.

            '
      summary: Deactivate your credentials
      tags:
      - Self
  /api-clients/self/credentials/{credentialId}:
    delete:
      description: 'Deletes a specific credential from your API client. You can only
        delete inactive credentials.

        '
      operationId: delete-self-credential
      responses:
        204:
          description: 'Credential removed.

            '
      summary: Remove your credential
      tags:
      - Self
    get:
      description: 'Returns details of a specific credential for your API client.
        To change the credential''s expiration date or toggle its activation status,
        run the [Update a credential](ref:put-client-credential) operation.

        '
      operationId: get-self-credential
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credential-200.json
              schema:
                $ref: schemas/credential-nosecret.yaml
          description: 'The response returns the credential.

            '
      summary: Get your credential
      tags:
      - Self
    parameters:
    - $ref: parameters/credentialId-path.yaml
    put:
      description: 'Updates the details of a specific credential for your API client.
        You can change the expiration date, description, or toggle the activation
        status. This isn''t the same as rotating a credential. For details, see [Rotate
        credentials](ref:rotate-credentials).

        '
      operationId: put-self-credential
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/get-credential-200.json
            schema:
              $ref: schemas/update-credential.yaml
        required: true
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credential-200.json
              schema:
                $ref: schemas/credential-nosecret.yaml
          description: 'The response returns the updated credential.

            '
      summary: Update your credential
      tags:
      - Self
  /api-clients/self/credentials/{credentialId}/deactivate:
    parameters:
    - $ref: parameters/credentialId-path.yaml
    post:
      description: 'Deactivates a specific credential for your API client. This doesn''t
        delete the client or the credentials. To update a specific credential, run
        the [Update your credential](ref:put-self-credential) operation.

        '
      operationId: post-self-credential-deactivate
      responses:
        204:
          description: 'Credential deactivated.

            '
      summary: Deactivate your credential
      tags:
      - Self
  /api-clients/{clientId}:
    get:
      description: 'Returns details about a given API client.

        '
      operationId: get-api-client
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/api-client-200.json
              schema:
                $ref: schemas/api-client.yaml
          description: 'The operation returns the API client.

            '
      summary: Get a client
      tags:
      - Clients
    parameters:
    - $ref: parameters/clientId-path.yaml
  /api-clients/{clientId}/account-switch-keys:
    get:
      description: 'The response object contains the `accountSwitchKeys` and `accountNames`
        you can access based on the permissions of the client. Once you have the `accountSwitchKeys`,
        you can make an API call to another account. To learn more, see [Manage many
        accounts with one API client](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).

        '
      operationId: get-client-account-switch-keys
      parameters:
      - $ref: parameters/search.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-account-switch-keys.json
              schema:
                $ref: schemas/client-account-switch-keys.yaml
          description: 'The response lists account switch keys.

            '
      summary: List account switch keys
      tags:
      - Clients
    parameters:
    - $ref: parameters/clientId-path.yaml
  /api-clients/{clientId}/credentials:
    get:
      description: 'Returns all credentials for a given API client.

        '
      operationId: get-client-credentials
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credentials-200.json
              schema:
                $ref: schemas/credentials.yaml
          description: 'The response lists credentials.

            '
      summary: List credentials
      tags:
      - Clients
    parameters:
    - $ref: parameters/clientId-path.yaml
    post:
      description: 'Creates a new credential for a given API client. Only the client''s
        owner may create credentials for the client. Credentials are in `active` status
        at creation. They expire two years from their creation date. However, when
        the API client''s permissions are based on Control Center permissions, credentials
        expire differently and follow the same rotation schedule listed for user passwords
        on those accounts. Run the [Update a credential](ref:put-client-credential)
        operation to change the expiration date, description, or status. Save the
        values from the response, such as the `credentialID`, for future use. This
        is the only time you''ll see the client secret. Save the credential at this
        time to avoid the need to create a new one.

        '
      operationId: post-client-credentials
      responses:
        201:
          content:
            application/json:
              example:
                $ref: examples/post-credentials-200.json
              schema:
                $ref: schemas/credential.yaml
          description: 'The response returns the created credential.

            '
      summary: Create a credential
      tags:
      - Clients
  /api-clients/{clientId}/credentials/deactivate:
    parameters:
    - $ref: parameters/clientId-path.yaml
    post:
      description: 'Deactivates all credentials for a given API client. This doesn''t
        delete the API client or the credentials. To deactivate a single credential,
        run the [Update a credential](ref:put-client-credential) operation and set
        the status to `INACTIVE`.

        '
      operationId: post-client-credentials-deactivate
      responses:
        204:
          description: 'Credentials deactivated.

            '
      summary: Deactivate credentials
      tags:
      - Clients
  /api-clients/{clientId}/credentials/{credentialId}:
    delete:
      description: 'Deletes a specific credential from a given API client. You can
        only delete inactive credentials.

        '
      operationId: delete-client-credential
      responses:
        204:
          description: 'Credential removed.

            '
      summary: Remove a credential
      tags:
      - Clients
    get:
      description: 'Returns details of a specific credential for a given API client.
        To change the credential''s expiration date or toggle its activation status,
        run the [Update credential for an API client](ref:put-client-credential) operation.

        '
      operationId: get-client-credential
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credential-200.json
              schema:
                $ref: schemas/credential-nosecret.yaml
          description: 'The response returns the credential.

            '
      summary: Get a credential
      tags:
      - Clients
    parameters:
    - $ref: parameters/credentialId-path.yaml
    - $ref: parameters/clientId-path.yaml
    put:
      description: 'Updates the details of a specific credential for a given API client.
        You can change the expiration date, description, or toggle the activation
        status. This isn''t the same as rotating a credential. For details, see [Rotate
        credentials](ref:rotate-credentials).

        '
      operationId: put-client-credential
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/get-credential-200.json
            schema:
              $ref: schemas/update-credential.yaml
        required: true
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credential-200.json
              schema:
                $ref: schemas/credential-nosecret.yaml
          description: 'The response returns the updated credential.

            '
      summary: Update a credential
      tags:
      - Clients
  /api-clients/{clientId}/credentials/{credentialId}/deactivate:
    parameters:
    - $ref: parameters/credentialId-path.yaml
    - $ref: parameters/clientId-path.yaml
    post:
      description: 'Deactivates a specific credential for a given API client. This
        doesn''t delete the API client or the other credentials.

        '
      operationId: post-client-credential-deactivate
      responses:
        204:
          description: 'Credential deactivated.

            '
      summary: Deactivate a credential
      tags:
      - Clients
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: api-clients.yaml
