info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Groups
  version: '2'
openapi: 3.0.0
paths:
  /user-admin/groups:
    get:
      description: 'List all groups in which you have a scope of `admin` for the current
        account and contract type. The account and contract type are determined by
        the access tokens in your API client.

        '
      operationId: get-groups
      parameters:
      - $ref: parameters/rolesFilterParamsActions_actions.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-response-groups.json
              schema:
                $ref: schemas/ListOfGroupResponse.yaml
          description: 'The response lists groups.

            '
      summary: List groups
      tags:
      - Groups
  /user-admin/groups/move:
    post:
      description: "Move a nested group under another group within the same parent\
        \ hierarchy. Run the [List users affected by moving a group](ref:get-move-affected-users)\
        \ operation to check which users would be affected if you were to move a group.\
        \ \n"
      operationId: post-groups-move
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/post-request-move-group.json
            schema:
              $ref: schemas/MoveGroupRequest.yaml
        required: true
      responses:
        204:
          description: 'Group moved.

            '
      summary: Move a group
      tags:
      - Move groups
  /user-admin/groups/move/{sourceGroupId}/{destinationGroupId}/affected-users:
    get:
      description: 'List users who would be affected if you were to move a group.
        Users may lose or gain access to resources depending on the roles and permissions
        of the new parent group. Users with a `userType` of `lostAccess` lose their
        access to the source group. If the `userType` is `gainAccess`, they gain access
        to the resources in the source group. Users who have inherited access to a
        group lose access to that group if it moves out of its the hierarchy that
        gives them those access rights. If the group moves to another parent group
        to which they have access, they still have access to the group you move. Likewise,
        when a group is moved to its new location, users who inherit their access
        rights from the new parent group gain access to the resources in the group
        you move.

        '
      operationId: get-move-affected-users
      parameters:
      - $ref: parameters/userType-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-response-affected-users.json
              schema:
                $ref: schemas/ListOfMoveUserResponse.yaml
          description: 'The response lists affected users.

            '
      summary: List users affected by moving a group
      tags:
      - Move groups
    parameters:
    - $ref: parameters/destinationGroupId-path.yaml
    - $ref: parameters/sourceGroupId-path.yaml
  /user-admin/groups/{groupId}:
    delete:
      description: 'You can only delete a sub-group, and only if that sub-group doesn''t
        include any users.

        '
      operationId: delete-group
      responses:
        204:
          description: 'Group deleted.

            '
      summary: Delete a group
      tags:
      - Groups
    get:
      description: 'Return a group''s details.

        '
      operationId: get-group
      parameters:
      - $ref: parameters/rolesFilterParamsActions_actions.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-response-group-details.json
              schema:
                $ref: schemas/GroupResponse.yaml
          description: 'The response returns the group.

            '
      summary: Get a group
      tags:
      - Groups
    parameters:
    - $ref: parameters/groupId-path.yaml
    post:
      description: 'Create a new group within a parent group you specify in the request.

        '
      operationId: post-group
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/post-request-group.json
            schema:
              $ref: schemas/GroupRequest.yaml
        required: true
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/post-response-group.json
              schema:
                $ref: schemas/GroupResponse.yaml
          description: 'The response returns the created group.

            '
      summary: Create a new group
      tags:
      - Groups
    put:
      description: 'Change the name of the group.

        '
      operationId: put-group
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/put-request-group.json
            schema:
              $ref: schemas/GroupRequest.yaml
        required: true
      responses:
        201:
          content:
            application/json:
              example:
                $ref: examples/put-response-group.json
              schema:
                $ref: schemas/GroupResponse.yaml
          description: 'The response returns the modified group.

            '
      summary: Modify a group's name
      tags:
      - Groups
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: groups-api.yaml
