info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: IP allowlists
  version: '2'
openapi: 3.0.0
paths:
  /user-admin/ip-acl/allowlist:
    get:
      description: 'List all CIDR blocks on your account''s allowlist. This allowlist
        is for the account designated by your API client.

        '
      operationId: get-allowlist
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-ip-acls.json
              schema:
                $ref: schemas/ip-acls-200.yaml
          description: 'The response lists CIDR blocks.

            '
      summary: List CIDR blocks
      tags:
      - CIDR blocks
    post:
      description: 'Add CIDR blocks to your account''s allowlist. You can add only
        one CIDR block at a time.

        '
      operationId: post-allowlist
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/post-ip-acl.json
            schema:
              $ref: schemas/post-ip-acl.yaml
        required: true
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/ip-acl-200.json
              schema:
                $ref: schemas/ip-acl-200.yaml
          description: 'The response returns the created CIDR block.

            '
      summary: Create a CIDR block
      tags:
      - CIDR blocks
  /user-admin/ip-acl/allowlist/disable:
    post:
      description: 'After you disable IP allowlist on your account, users can access
        Control Center regardless of their IP address or who assigns it.

        '
      operationId: post-allowlist-disable
      responses:
        204:
          description: 'IP allowlist disabled.

            '
      summary: Disable IP allowlist
      tags:
      - Allowlists
  /user-admin/ip-acl/allowlist/enable:
    post:
      description: 'Before you enable IP allowlist on your account, add at least one
        IP address to allow access to Control Center. The allowlist can''t be empty
        with IP allowlist enabled.

        '
      operationId: post-allowlist-enable
      responses:
        204:
          description: 'IP allowlist enabled.

            '
      summary: Enable IP allowlist
      tags:
      - Allowlists
  /user-admin/ip-acl/allowlist/status:
    get:
      description: 'Indicates whether IP allowlist is enabled or disabled on your
        account.

        '
      operationId: get-allowlist-status
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/state-ip-acl-account.json
              schema:
                $ref: schemas/account-status.yaml
          description: 'The response verifies the IP allowlist status.

            '
      summary: View IP allowlist status
      tags:
      - Allowlists
  /user-admin/ip-acl/allowlist/validate:
    get:
      description: 'Check the format of your CIDR blocks. To validate, pass the CIDR
        block or an individual IP address in the `cidrblock` query parameter. Encode
        any slash characters as `%2F`.

        '
      operationId: get-allowlist-validate
      parameters:
      - $ref: parameters/cidrblock-query.yaml
      responses:
        204:
          description: 'CIDR block is valid.

            '
      summary: Validate CIDR blocks
      tags:
      - CIDR blocks
  /user-admin/ip-acl/allowlist/{cidrBlockId}:
    delete:
      description: 'After you delete a CIDR block from the allowlist, any requests
        from IP addresses you deleted fail the next time someone tries to log in from
        that address. Users accessing Control Center from an IP address you delete
        aren''t automatically logged out of Control Center at the time you delete
        the IP address. With IP allowlist enabled for the account, you can''t delete
        the last CIDR block in the allowlist or the CIDR block allowing access to
        the current user. There are no restrictions with IP allowlist disabled on
        the account.

        '
      operationId: delete-allowlist-cidrblockid
      responses:
        204:
          description: 'CIDR block deleted.

            '
      summary: Delete a CIDR block
      tags:
      - CIDR blocks
    get:
      description: 'Get a specific CIDR block.

        '
      operationId: get-allowlist-cidrblockid
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/ip-acl-200.json
              schema:
                $ref: schemas/ip-acl-200.yaml
          description: 'The response returns the CIDR block.

            '
      summary: Get a CIDR block
      tags:
      - CIDR blocks
    parameters:
    - $ref: parameters/cidrBlockId-path.yaml
    put:
      description: 'Enable or disable an existing CIDR block, update comments, IP
        address, or range in the CIDR block. Note that you can only update a CIDR
        block with IP allowlist enabled on the account. There are several CIDR blocks
        on the allowlist and your attempt to make changes to the CIDR block is from
        an IP address that''s on the allowlist. You can''t edit the last CIDR block
        in the allowlist or the CIDR block allowing access to the current user.

        '
      operationId: put-allowlist-cidrblockid
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/post-ip-acl.json
            schema:
              $ref: schemas/post-ip-acl.yaml
        required: true
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/ip-acl-200.json
              schema:
                $ref: schemas/ip-acl-200.yaml
          description: 'The response returns the modified CIDR block.

            '
      summary: Modify a CIDR block
      tags:
      - CIDR blocks
servers:
- url: https://{hostname}/identity-management/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: ip-acl.yaml
