info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Credentials
  version: '1'
openapi: 3.0.0
paths:
  /open-identities/tokens/{accessToken}:
    get:
      description: 'View an API client''s details. This operation lets you get a specific
        API client by passing the client''s token in the request.

        '
      operationId: get-identity-access-token
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/open-identity-by-access-token-200.json
              schema:
                $ref: schemas/identity.yaml
          description: 'The response provides API client''s details.

            '
      summary: Get a client by its access token
      tags:
      - Tokens
    parameters:
    - $ref: parameters/access-token-path.yaml
  /open-identities/{openIdentityId}/account-switch-keys:
    get:
      description: 'The response object contains the `accountSwitchKeys` and account
        names you can access based on the permissions of your API client. Once you
        have the `accountSwitchKeys` you need, [you can make an API call to another
        account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).

        '
      operationId: get-account-switch-keys
      parameters:
      - $ref: parameters/search-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/account-switch-keys-200.json
              schema:
                $ref: schemas/get-open-identities-openidentityid-account-switch-keys-response.yaml
          description: 'The response lists account switch keys.

            '
      summary: List account switch keys
      tags:
      - Account switch keys
    parameters:
    - $ref: parameters/open-identity-id-path.yaml
  /open-identities/{openIdentityId}/credentials:
    get:
      description: 'Get an API client''s credentials.

        '
      operationId: get-identity-credentials
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credentials-200.json
              schema:
                $ref: schemas/credentials.yaml
          description: 'The response returns credentials.

            '
      summary: List credentials
      tags:
      - Credentials
    parameters:
    - $ref: parameters/open-identity-id-path.yaml
    post:
      description: 'Create a new credential for an API client. Only the owner of an
        identity can create credentials for it.  Credentials are in `active` status
        at creation, and by  default expire two years from their creation date.  However,
        credentials expire differently when the API client is based on Control Center
        user permissions, and follow the same rotation schedule  listed for user passwords
        on those accounts. Run the [Update a credential](ref:put-identity-credential)
        operation to change the expiration date, description or status.  Save information
        from the response information like the `credentialID` for future use.  This
        is the only time you see the client secret. If you don''t save it at this
        time, you''ll need to create a new credential.

        '
      operationId: post-identity-credential
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/post-credentials-200.json
              schema:
                $ref: schemas/credential.yaml
          description: 'The response provides created credentials.

            '
      summary: Create a credential
      tags:
      - Credentials
  /open-identities/{openIdentityId}/credentials/deactivate:
    parameters:
    - $ref: parameters/open-identity-id-path.yaml
    post:
      description: 'Deactivate all credentials for an API client. This doesn''t delete
        the API identity or the credentials. To deactivate a single credential, run
        the [Update a credential](ref:put-identity-credential) operation and set the
        status to `INACTIVE`.

        '
      operationId: post-identity-credential-deactivate
      responses:
        200:
          description: 'Credentials deactivated.

            '
      summary: Deactivate all credentials
      tags:
      - Credentials
  /open-identities/{openIdentityId}/credentials/{credentialId}:
    delete:
      description: 'Delete a credential. You can only delete inactive credentials.

        '
      operationId: delete-identity-credential
      responses:
        200:
          description: 'Credential removed.

            '
      summary: Remove a credential
      tags:
      - Credentials
    get:
      description: 'Get details for a single credential. Use [Update a credential](ref:put-identity-credential)
        to change the credential''s expiration date, or toggle the credential''s activation
        status.

        '
      operationId: get-identity-credential
      parameters:
      - $ref: parameters/actions-query.yaml
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/get-credential-200.json
              schema:
                $ref: schemas/credential-nosecret.yaml
          description: 'The response returns credentials.

            '
      summary: Get a credential
      tags:
      - Credentials
    parameters:
    - $ref: parameters/credential-id-path.yaml
    - $ref: parameters/open-identity-id-path.yaml
    put:
      description: 'Edit credential details. You can change the expiration date, description,
        or toggle the activation status. This isn''t the same as rotating a credential.
        For credential rotation, see [Rotate credentials](ref:rotate-credentials).

        '
      operationId: put-identity-credential
      requestBody:
        content:
          application/json:
            example:
              $ref: examples/put-credential.json
            schema:
              $ref: schemas/update-credential.yaml
        required: true
      responses:
        200:
          content:
            application/json:
              example:
                $ref: examples/put-credential.json
              schema:
                $ref: schemas/credential-nosecret.yaml
          description: 'The response provides updated credentials.

            '
      summary: Update a credential
      tags:
      - Credentials
servers:
- url: https://{hostname}/identity-management/v1
x-akamai:
  auth-type: EDGE_GRID
  file-path: open-identities.yaml
