name: productId
in: query
description: |-
  Filters down results for a specific product, and allows listing data sets available for it. In the [List data set fields](ref:get-dataset-fields) operation, you can provide one `productId` per API call.
  
x-akamai:
  file-path: parameters/product-id-query.yaml
schema:
  type: string
  example: Adaptive_Media_Delivery
